### ISSUE TITLE
Got an error when unzip a zip file which contain a zip file

### ISSUE THREAD

**Issue by GrayLand119** [weichsel/ZIPFoundation#102]
# Summary
Got an error when unzip a zip file which contain a zip/bin file

# Steps to Reproduce
1.  zipItem  "blablabla/A.zip" to "blablabla/B.zip"  successfully.
2. unzipItem "blablabla/B.zip" got the error blow:

Error Domain=NSCocoaErrorDomain Code=258 "The item couldn’t be opened because the file name “A.zip” is invalid."

# Expected Results
error is nil.

# Actual Results
error is not nil, Error Domain=NSCocoaErrorDomain Code=258 "The item couldn’t be opened because the file name “s02_0004_0120.zip” is invalid."

# Regression & Version

Using ZIPFoundation (0.9.8)

# Related Link

**Comment by weichsel** [comment]
Hi,

I just tested the scenario you are describing with the following sample code (using one of the .zip files of the test suite as input):
```swift
guard let zipFileURL = Bundle.main.url(forResource: "test", withExtension: "zip") else {
            return
        }
        var destURL = URL(fileURLWithPath: NSTemporaryDirectory())
        destURL.appendPathComponent(ProcessInfo.processInfo.globallyUniqueString)
        destURL.appendPathExtension("zip")
        try? FileManager().zipItem(at: zipFileURL, to: destURL)
        var finalURL = URL(fileURLWithPath: NSTemporaryDirectory())
        finalURL.appendPathComponent(ProcessInfo.processInfo.globallyUniqueString)
        try? FileManager().unzipItem(at: destURL, to: finalURL)
```

I was able to successfully extract the nested zip with `unzipItem`.  
Can you share the code (and ideally the .zip file) you are using.

**Comment by GrayLand119** [comment]
Thank you for reply,

I found my code is incorrect,  I used your sample code can successfully extract .
I used the method `URL.init(string: toPath!)` to create a Url and it's incorrect.

`URL.init(fileURLWithPath:toPath!)` is  work fine.

```
        guard let zipFileURL = Bundle.main.url(forResource: "blinky_s132", withExtension: "zip") else {
            return
        }

        let toPath = NSSearchPathForDirectoriesInDomains(FileManager.SearchPathDirectory.cachesDirectory, FileManager.SearchPathDomainMask.userDomainMask, true).first
        
        // Work!
        let finalUrl = URL.init(fileURLWithPath:toPath!)
        try? FileManager().unzipItem(at: zipFileURL, to: finalUrl)
        // Doesn't work!
//        let finalUrl = URL.init(string: toPath!)
//        try? FileManager().unzipItem(at: zipFileURL, to: finalUrl!)
```
