### ISSUE TITLE
Crashes in Swift 5 in Debug mode

### ISSUE THREAD

**Issue by xavierLowmiller** [weichsel/ZIPFoundation#106]
# Summary

In Swift 5, I get some `fatalError`s, such as:
- `Fatal error: UnsafeRawBufferPointer.load out of bounds`
- `Fatal error: load from misaligned raw pointer`

These are only present in `DEBUG` mode, though, so maybe it's fine?

# Steps to Reproduce

The errors are reproducible using ZIPFoundation's test suite:

1. Set `SWIFT_VERSION` to 'Swift 5'
1. Set the Build Configuration in the Scheme to 'Debug'

# Expected Results

All tests pass

# Actual Results

Some `fatalError`s related to UnsafePointers are triggered

# Regression & Version

Xcode 10.2 and Swift 5

**Comment by weichsel** [comment]
Hi,
Thanks for pointing this out - The current `development` contains a bug that I introduced when I switched to the Swift 5.0 version of `withUnsafeBytes:`. The crash will be fixed after #105 got merged.

**Comment by xavierLowmiller** [comment]
Oh, that's great to hear!

I'll close this then ✅
