### ISSUE TITLE
Performance improvement: consider using FileManager.default.url(for:,in:,appropriateFor:, create:) instead of NSTemporaryDirectory()

### ISSUE THREAD

**Issue by Mark-s99** [weichsel/ZIPFoundation#108]
**Suggestion:**

Performance of removing an entry could be improved a bit for archives that reside on volumes, other than the main volume (i.e. the volume of the user's home directory) by using a temporary directory on the same external volume and thus avoiding copying the temporary archive across volumes.

**Details:**

`NSTemporaryDirectory()` always returns the path of the temporary directory for the current user. If a zip archive is on a different volume, the performance of removing an entry could be improved by using `FileManager.url(for:in:appropriateFor:create:)` instead. The FileManager method _returns a temporary directory on the same volume as the target file_ so that replacing the original with the temporary new version of the archive can be achieved in one step.

This is also the recommended way by Apple: https://developer.apple.com/documentation/foundation/1409211-nstemporarydirectory

**Code:**

In Archive+Writing.swift, around line 150 in `Archive.remove()`, replace:

    let tempArchiveURL =  URL(fileURLWithPath: NSTemporaryDirectory()).appendingPathComponent(uniqueString)

with: 

    let tempArchiveURL = try FileManager().url(for: .itemReplacementDirectory, in: .userDomainMask, appropriateFor: self.url, create: true).appendingPathComponent(uniqueString)

https://github.com/weichsel/ZIPFoundation/blob/92d56accedbd385ae39d3521a46524ea07cab008/Sources/ZIPFoundation/Archive%2BWriting.swift#L150

**Comment by weichsel** [comment]
Good point - I will tag this with the "Help Wanted" label. Maybe someone finds time to test this through.  
If no-one picks up this issue, I can see if I can implement it for the next release.
