### ISSUE TITLE
App crash Thread 21: signal SIGABRT

### ISSUE THREAD

**Issue by alexanderkhitev** [weichsel/ZIPFoundation#114]
Hello I faced app crash here
```
try fileManager.unzipItem(at: archiveURL, to: packDirURL, progress: progress)
```
when I updated from from 0.9.8 to 0.9.9 version

**Comment by weichsel** [comment]
Hi Alexander,

How are you integrating ZIP Foundation into your project. And what Xcode/Swift versions are you using?  
The Swift toolchain currently does not provide the ability to ship binary compatible frameworks.  
Please have a look at this [issue](https://github.com/weichsel/ZIPFoundation/issues/112). Maybe your setup is similar.  
In my personal experience, the most flexible way to integrate 3rd party Swift frameworks is via `carthage --no-build` and referencing the dependency `xcodeproj` in your project workspace. (As described in the Carthage section of the ZIP Foundation readme).

**Comment by alexanderkhitev** [comment]
Hi @weichsel , 
thanks for quick response 
I use CocoaPods for integrating 3rd party frameworks, Xcode Version 10.2.1 (10E1001), Swift 5.

**Comment by weichsel** [comment]
Is ZIP Foundation a direct dependency in your project, or is it a transitive dependency (e.g. imported by another CocoaPod)?  
I just performed a quick test where I integrated `ZIPFoundation` via CocoaPods in a small test iOS project. Everything seems to work as expected.  
Can you provide more details about your setup?

**Comment by alexanderkhitev** [comment]
@weichsel 
ZIPFoundation is direct dependency in our project.

**Comment by alexanderkhitev** [comment]
Maybe I can do a demo project after a while.

**Comment by weichsel** [comment]
If you find some time to provide a demo project, that'd be great. 
Can you please also provide the platform (iOS, macOS, ...) you are working on and the CocoaPods version you are using.

**Comment by alexanderkhitev** [comment]
Platform is IOS (App crash happened on iOS 12.2)
CocoaPods version is 1.5.3

**Comment by weichsel** [comment]
Thanks.  
I tested also with iOS 12.2 but my CocoaPods version is newer 1.6.1 . 
Maybe clearing CocoaPods build artefacts and updating CocoaPods solves your problem?

**Comment by alexanderkhitev** [comment]
@weichsel I'll try do it today

**Comment by alexanderkhitev** [comment]
Hello @weichsel !
I updated CocoaPods to 1.6.1 and it fixed app crash problem, thank you so much!

**Comment by weichsel** [comment]
Glad I could help!
