### ISSUE TITLE
Value of type 'FileManager' has no member 'zipItem'

### ISSUE THREAD

**Issue by mkabatek** [weichsel/ZIPFoundation#115]
# Summary

I encountered the following error when trying to use ZIPFoundation:

```
Value of type 'FileManager' has no member 'zipItem'
```

Possibly add `import ZIPFoundation` on the `README.md` for more clarity.

**Comment by weichsel** [comment]
Hi,

Thanks for your feedback. 
While I tried to keep the code snippets self-contained and compileable, I did not include setup (like `imports`, teardown and error handling code to keep the snippets short and easy to read.

**Comment by chadmonahan** [comment]
would have saved me an hour

great tool though, thanks!

**Comment by hispeedsurfer** [comment]
> # Summary
> 
> I encountered the following error when trying to use ZIPFoundation:
> 
> ```
> Value of type 'FileManager' has no member 'zipItem'
> ```
> 
> Possibly add `import ZIPFoundation` on the `README.md` for more clarity.

Yes, please add this to the README.md
