### ISSUE TITLE
How to zip multiple files not in the same folder?

### ISSUE THREAD

**Issue by mkabatek** [weichsel/ZIPFoundation#116]
Hello,

I'm trying to zip multiple files that are contained in an array `[URL]()` I'm not entirely sure how to do this with ZIPFoundation and the example only shows how to zip a single file or a folder with multiple files.

**Comment by weichsel** [comment]
Hi,

The "Zipping Files and Directories" section only covers the high-level `zipItem(:at:to)` method of ZIP Foundation's `FileManager` extension.  

To add individual entries to an archive, you can have a look at the ["Adding and Removing Entries"](https://github.com/weichsel/ZIPFoundation#adding-and-removing-entries) section. It covers individual entry addition.  

In you case you can do something like:   
```swift
for fileURL in urls {
    try archive.addEntry(with: fileURL.lastPathComponent, relativeTo:fileURL.deletingLastPathComponent())
}
```
