### ISSUE TITLE
ZIP64 Support

### ISSUE THREAD

**Issue by levigroker** [weichsel/ZIPFoundation#118]
The original .ZIP format had a 4 GiB (2^32 bytes) limit, which is no longer relevant on 64 bit architectures and, since version 4.5 of the specification (currently at 6.3.6), has been supplanted by ZIP64, which increases the limits to 16EiB (2^64 bytes). 

ZIPFoundation should be able to handle archives larger than 4 GiB by adopting the ability to work with ZIP64 archives.

https://en.wikipedia.org/wiki/Zip_(file_format)#ZIP64
https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT

**Comment by weichsel** [comment]
Yes, ZIP64 support would be great - I'll assign a "Help Wanted" label to this issue. Maybe someone wants to work on that and submits a PR.

**Comment by mvolpato** [comment]
What is needed to implement this? Does it consists only in changing parameter and variable types?

**Comment by levigroker** [comment]
@mvolpato It's a bit more involved than that. There's basically a branch in the archive structure. Take a look at the two links I posted for more details.

**Comment by weichsel** [comment]
When implementing ZIP64 support, it'd be probably good if we find a way to split up the PR into several smaller ones.  
I haven't looked into implementing it so far, but probably it would work to add the additional structures (`EndOfCentralDirectoryRecord64` & `EndOfCentralDirectoryLocator64`) first and then try to implement archive reading support with them.  
Writing & updating could then be implemented in a separate PR.

**Comment by bparousis** [comment]
Hello!  I was just wondering if anyone was working on this issue.  Any updates?

**Comment by weichsel** [comment]
Hi,

I am currently not actively working on ZIP64 support and AFAIK nobody has taken up that project yet.

**Comment by bparousis** [comment]
Thanks for the update!

**Comment by Ckitakishi** [comment]
Hi, I'm wondering if anyone is working on this?  
If not, I would like to handle this issue since my team is using ZIPFoundation and we need zip64 support~


I made a rough plan:
### Step1. Zip
  - **Version needed to extract**
      - Set this value as 45 for using zip64.
  - **Zip64 Extended Information Extra Field**. Optional, use extra field only when: 
      - Local File Header
          - compressed size >= `UInt32.max`
          - uncompressed size >= `UInt32.max`
          -  Spec: This entry in the Local header MUST include BOTH original and compressed file size fields.
      - Central Directory File Header
          - compressed size >= `UInt32.max`
          - uncompressed size >=` UInt32.max`
          - offset of local file header >= `UInt32.max`
  - **Zip64 end of central directory record**. Optional, use only in the following cases:
      - Total number of entries > `UInt16.max`
      - Offset of central directory >= `UInt32.max`
  - **Zip64 end of central directory locator**
      - Zip64 end of central directory locator is optional too. However, if zip64 end of central directory record exists, then locator must exists. Same for non-existent case.

### Step2. Unzip
Almost same with zip. And:
- **Data descriptor**
    - For zip64, the compressed size and uncompressed size are changed to 8 bytes.
    
### Step3. [Better to have, but the priority is low] Writing policy
```swift
enum WritingPolicy {
    case automatic // Default, Only use zip64 when needed
    case never // In the cases of zip64 is needed, throw errors instead of using zip64
    case always // Always using zip64 even if it's unnecessary
}
```

**Comment by billparousis** [comment]
I would love to see supported added for this! 👍

**Comment by billparousis** [comment]
@Ckitakishi I'm happy to lend a hand with testing or code reviews, etc.  I'm eager to see this feature added to ZipFoundation.  I think it's much needed.  Thanks for volunteering to take this on!

**Comment by weichsel** [comment]
@Ckitakishi 
> Hi, I'm wondering if anyone is working on this?
> If not, I would like to handle this issue since my team is using ZIPFoundation and we need zip64 support~

ATM no one is working on this, but if you can kickstart this feature, I'll do my best to help to get it landed.  
Your plan looks great and should provide a good starting point. Another thing we could try is to utilize Swift Generics where possible. This would allow us to keep the methods and the API the same and only switch e.g. between `EndOfCentralDirectoryRecord` and `EndOfCentralDirectoryRecord64`.

**Comment by Ckitakishi** [comment]
@billparousis Wow, it will be very helpful! I hope you will be one of the reviewers.

**Comment by Ckitakishi** [comment]
@weichsel 
If so, I would like to take this issue~
Thanks for your great advice, I'll try to keep the code as simple as possible and avoid code redundancy.

I have a question, it seems that the file length is limited to 400 lines, is it possible to change the length limit? Or should I split the code into smaller files?

**Comment by weichsel** [comment]
> If so, I would like to take this issue~
Thanks for your great advice, I'll try to keep the code as simple as possible and avoid code redundancy.

👍 Great - let me know where I can help.

> I have a question, it seems that the file length is limited to 400 lines, is it possible to change the length limit? Or should I split the code into smaller files?

We are using the default ruleset of Swiftlint, which IMO is reasonable and provides a good baseline.  

Some files are almost at the 400 line limit but I think we can ignore that at first. Later we can split out extensions that are grouped by purpose (e.g. Archive+ZIP64) or we move the basic structs (like the central directory structure etc.) into dedicated files.

**Comment by Ckitakishi** [comment]
> Great - let me know where I can help.

Thank you! I will post comment here if I have any question.

> Some files are almost at the 400 line limit but I think we can ignore that at first. Later we can split out extensions that are grouped by purpose (e.g. Archive+ZIP64) or we move the basic structs (like the central directory structure etc.) into dedicated files.

No problem, let's keep using the default SwiftLint.
I will follow my ideas first and then come back later to discuss the the file structs.

**Comment by Ckitakishi** [comment]
@weichsel Hi, I'm sorry for late, I've been very busy the past two months..

The first part of zip64 support is now complete(https://github.com/Ckitakishi/ZIPFoundation/pull/4), I'd like to make a p-r, however, I think the base branch shouldn't be `development` as zip64 support is still in progress, would you mind helping me to create feature branch like `feature/zip64`..? (Seems I can't do that)

**Comment by weichsel** [comment]
> @weichsel Hi, I'm sorry for late, I've been very busy the past two months..

No problem - can totally relate to that :) 

> The first part of zip64 support is now complete(Ckitakishi#4), I'd like to make a p-r, however, I think the base branch shouldn't be development as zip64 support is still in progress, would you mind helping me to create feature branch like feature/zip64..? (Seems I can't do that)

Took a quick glance over your PR - That looks like a great start!

I suggest the following workflow:
- You merge your `zip64-zip-pt1` branch into your `zip64` branch  (which is based on the origin `development` I suppose) ...
- ... then you open your PR from there
- I'll do my best to review the PR ASAP
- We work on your branch and finish it (but don't merge yet)
- We pull in from `development` if anything changes there (it's currently very low traffic)
- Follow-up PRs (read support, ...) will be based on your `zip64` base branch
- When everything's done, we merge into `development`

**Comment by Ckitakishi** [comment]
> I suggest the following workflow:

Sounds good, but I'd like to confirm, do you mean:
1. `my zip64-zip-pt1` => `my zip64` => (review, but do not merge) => `origin development`?
2. Follow-up branch(es) => (review, **in my repository? or in above PR?**)  => `my zip64`

**Comment by weichsel** [comment]
> my zip64-zip-pt1 => my zip64 => (review, but do not merge) => origin development?

Yes that should work. Your `zip64` branch will be the one where we "collect" all zip64 related PRs.

> Follow-up branch(es) => (review, in my repository? or in above PR?) => my zip64

I never tried it, but there should be no problem to open PRs on your "fork" of ZIPFoundation. 
So when working on `pt2`, you branch-off `zip64` (or `zip64-zip-pt1` if we haven't merged that already). When you open the PR, you should be able to select `zip64` (or `zip64-zip-pt1`) as base. This will keep the diff focused on the `pt2` changes.

**Comment by Ckitakishi** [comment]
No problem for me, just concerned that if someone wants to check the follow-up PR(s)' review history, he needs to check it on my fork of ZIPFoundation. If it's okay, I'll merge my `zip64-zip-pt1` into `zip64` and open a PR based on `development`, then request you review~

**Comment by weichsel** [comment]
Yes, works for me. 👍
