### ISSUE TITLE
Expose API to skip CRC32 calculation at top level

### ISSUE THREAD

**Issue by Mark-s99** [weichsel/ZIPFoundation#120]
CRC32 calculation causes a performance impact. Currently there is a low-level API to skip CRC3 calculation in:

https://github.com/weichsel/ZIPFoundation/blob/e1c406df93423ff867b35c743aca59632d0c1961/Sources/ZIPFoundation/Data%2BSerialization.swift#L45

However, that flag is not exposed in the higher level API, such as `Archive+Reading.swift`.

**Describe the solution you'd like**
Please consider exposing `skipCRC32:Bool` in methods in `Archive+Reading.swift`.

**Comment by weichsel** [comment]
The `skipCRC32` parameter is currently only used during entry removal.  
To make CRC32 checks optional during all reads, we'd have to add an additional parameter to all high level read method _and_ the low level method for compressed reading (`consumePart` is only used for uncompressed reading).

**Comment by Mark-s99** [comment]
Ok, no worries. I noticed a 10x performance difference when reading uncompressed entries. For now, I’ve exposed the flag specifically in the code path I’m using. Reading an archive with about 40 image files takes 160 ms compared to 1900 ms with the checksum. 

Would you be open to exposing the flag at all in the official repository? If I find the time, I could add this and send a pull-request.

**Comment by weichsel** [comment]
Yes, exposing an optional `skipCRC32` parameter for read operations would work for me. 
A PR would be very welcome.
