### ISSUE TITLE
Archive addEntry requires same filesystem structure

### ISSUE THREAD

**Issue by levigroker** [weichsel/ZIPFoundation#122]
# Summary

The method `addEntry(with path: String, relativeTo baseURL: URL, compressionMethod: CompressionMethod = .none, bufferSize: UInt32 = defaultWriteChunkSize, progress: Progress? = nil) throws` does not allow the caller to build an archive entry which has a different directory structure than that of the filesystem.

Additionally, `addEntry(...` requires requires a real directory to exist on the filesystem when adding a directory archive entry.

# Steps to Reproduce

Imagine wanting to create an archive with an internal structure which differs from the structure present on the file system. This API does not allow for abstract entries to be created.

# Expected Results

The API should allow for entries to be placed inside the archive at arbitrary locations regardless of their place on the filesystem.

# Actual Results

One must arrange the filesystem to match the desired archive structure prior to utilizing this API.

# Suggestions

The API could be changed to decouple the archive path from the URL. Something like `addEntry(as path: String, from url: URL?, ...` which allows the caller to construct the resulting archive path in any desired manner, while optionally placing the content from the given URL at the path location in the archive. The optional from url would allow for a directory entry to be added without needing to reference the filesystem, since the contents of this directory on the filesystem are ignored (see #121 ).

**Comment by tp** [comment]
I had the same desire, and made it work with this extension method (might be adapt for anyones more specific needs, but should be an OK starting point (at least for small files, not sure if there are any hidden performance issues inside)):

```swift
public extension Archive {
  func addFileEntry(url: URL, as path: String) throws {
    let data = try Data(contentsOf: url)
    let size = data.count
    
    try self.addEntry(with: path, type: .file, uncompressedSize: UInt32(size),
                          compressionMethod: .deflate,
                          provider: { (position, bufferSize) -> Data in
                             let upperBound = Swift.min(size, position + bufferSize)
                             let range = Range(uncheckedBounds: (lower: position, upper: upperBound))
                            return data.subdata(in: range)
     })
  }
}
```

**Comment by roznet** [comment]
I had the same issue/need. I built a pull Request #193 that added a new api that achieves this
```swift
func addEntry(with path: String, fileURL : URL, compressionMethod: CompressionMethod = .none,
                         bufferSize: UInt32 = defaultWriteChunkSize, progress: Progress? = nil) throws 
```
