### ISSUE TITLE
The name of sub-directory

### ISSUE THREAD

**Issue by marinofaggiana** [weichsel/ZIPFoundation#124]
Hi, when I try? FileManager().unzipItem(at: source, to: destination) the source file create a directory inside destination with the files, how I can know the name of this directory ?

**Comment by levigroker** [comment]
@weichsel might have more to say, and I don't speak for him, but I have a couple educated thoughts that may be helpful.

The zip archive you're decompressing sounds like it has a directory entry at it's root, which contains the remaining contents of the archive, but this is not a requirement of the ZIP format. An archive could contain many items all at the root level, which, when unarchived, would end up in the destination directory.

A couple approaches to consider:

1. Look inside the archive to determine the root entry (or entries). This can be done with code like

```
if  let archive = Archive(url: url, accessMode: .read) {
    archive.forEach({ (entry) in
        print("entry: \(entry.path)");
    })
}
```

2. Set an empty (temporary) directory as the destination and then use `FileManager` `contentsOfDirectory()` to list the contents of the destination directory.

**Comment by weichsel** [comment]
Hi,

As @levigroker already pointed out, you can determine the directory/filenames within the archive either by iterating over its contents or by enumerating the directory contents after unzipping.  

If your source file was also created with ZIP Foundation, and you want to avoid the root directory entry, you can use the optional `shouldKeepParent` parameter when [creating the archive](https://github.com/weichsel/ZIPFoundation#zipping-files-and-directories).
