### ISSUE TITLE
Archive init should throw

### ISSUE THREAD

**Issue by levigroker** [weichsel/ZIPFoundation#126]
# Summary
The `init` for `Archive` currently is optional, but should throw instead.

# Steps to Reproduce

`public init?(url: URL, accessMode mode: AccessMode, preferredEncoding: String.Encoding? = nil)`
# Expected Results

`public init(url: URL, accessMode mode: AccessMode, preferredEncoding: String.Encoding? = nil) throws`

# Discussion

With the present implementation any errors encountered by the initialization process are obscured and `nil` is simply returned. If the caller desires this behavior they can simply use `try?` on an `init` method which throws, otherwise the underlying errors should be thrown so the caller can better understand the failure.

**Comment by pwoszczek** [comment]
This apparently causes returning  archive object with no contents for some archives (for example created on MacOS), although the files are there and unpacking is working with https://github.com/marmelroy/Zip. There is no crash nor error returned.
