### ISSUE TITLE
Upgrade to SWIFT 5+

### ISSUE THREAD

**Issue by esbenr** [weichsel/ZIPFoundation#127]
**Is your feature request related to a problem? Please describe.**
Can not upgrade to Swift 5+ since ZipFoundation is only Swift 4.2.

**Describe the solution you'd like**
Update to swift 5+

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by weichsel** [comment]
Hi,

ZIP Foundation is ready for Swift 5.0 but it supports Swift versions from 4.0 - 5.0. The `SWIFT_VERSION` in the Xcode project is kept at 4.0 for the moment to keep the project compilable for people that integrate via Carthage and still use an Xcode version < 10.2.  

The Swift 5.x toolchains are backwards compatible. So you can use Xcode 10.2 with the Swift 5 toolchain to compile dependencies that have a lower `SWIFT_VERSION`.  

Which dependency manager are you using?
