### ISSUE TITLE
pod package ZIPFoundation.podspec 

### ISSUE THREAD

**Issue by wjc1wjc2wjc3** [weichsel/ZIPFoundation#131]
when i run 
'pod package ZIPFoundation.podspec ' on terminal of mac , show: fatal error module map file '/var/folders/r1/25fh_v497ss15_1xy6h25vkw0000gn/T/cocoapods-6i6z3puq/build/Release-iphonesimulator/ZIPFoundation/ZIPFoundation.modulemap' not found

  how to solve it ?

**Comment by weichsel** [comment]
Hi, 

I have no experience with packaging with CocoaPods. The podspec of ZIP Foundation does not use any advanced CP features - so packaging should be straight forward 🤷‍♂️ 
There is an issue that sounds very similar in the CocoaPods issue tracker: https://github.com/CocoaPods/cocoapods-packager/issues/211
Maybe you can ask for help there.

**Comment by wjc1wjc2wjc3** [comment]
hi,
   thank you。 it seems to nobody sovle it
