### ISSUE TITLE
Can I attach archive to MFMailComposeViewController?

### ISSUE THREAD

**Issue by fraserscottmorrison** [weichsel/ZIPFoundation#132]
Hi, I need to zip up some logs and send them as a mail attachment

MFMailComposeViewController has a method for attachments func addAttachmentData(_ attachment: Data, mimeType: String, fileName filename: String)

But it only accepts a Data object. Is there an easy way to get the Data of the zip directly, or do I need to save to file, then read the data from file, then delete the file?

**Comment by fraserscottmorrison** [comment]
Hi, I need to zip up some logs and send them as a mail attachment

MFMailComposeViewController has a method for attachments `func addAttachmentData(_ attachment: Data, mimeType: String, fileName filename: String)`

But it only accepts a Data object. Is there an easy way to get the Data of the zip directly, or do I need to save to file, then read the data from file, then delete the file?

**Comment by weichsel** [comment]
Creating in-memory archives is currently not supported. There is an open PR (#78) to add that functionality, but it's unfinished.  

In the meantime you'll have to use a temp file and read the data from there.
