### ISSUE TITLE
Suggestion: Replace CRC32 with call to zlib for better performance?

### ISSUE THREAD

**Issue by MrMage** [weichsel/ZIPFoundation#135]
**Is your feature request related to a problem? Please describe.**
Despite #40, calculating the CRC32 is still slow, especially in debug builds. Given that `zlib` [exposes a CRC32 method](https://rosettacode.org/wiki/CRC-32#Swift) and `zlib` ships with all Macs, would you be open to replacing the built-in CRC32 computation with a call to `zlib`'s `crc32` method?

**Describe the solution you'd like**
`Data.crc32` calls into `zlib` instead of implementing the CRC32 computation itself.

**Describe alternatives you've considered**
Keep things as is, accepting slow performance in debug builds.

**Comment by weichsel** [comment]
Hi Daniel,

I am aware of the slow performance of the built-in CRC32 method 🙁 but I try to keep the framework as self-contained as possible.  
The `DEBUG` version of `crc32(checksum:)` is ~ an order of magnitude slower than the `RELEASE` version. (And it gets even worse when you increment the `SWIFT_VERSION` to 5 and use the latest toolchain in the Xcode 11 betas). 

I have no clue why that relatively simple piece of code is _so_ slow when compiled unoptimized.  
The Time Profiler output is also hard to interpret because it contains a lot of `<Unknown Address> `sections. 🤷‍♂️

![Screenshot 2019-08-21 at 22 45 16](https://user-images.githubusercontent.com/1577319/63467533-facd2480-c465-11e9-856c-da30ecdd6c86.png)

I assume the slow CRC checks are holding you back during debugging? 
Would it help if we implement #120 ? That would allow you to conditionally turn off checksumming during debugging.

**Comment by MrMage** [comment]
Thank you for the elaboration! My app automatically creates a ZIP backup archive once per week, so if I could disable writing CRC32's to the ZIP archive in debug builds that would work. Not sure if #120 would also cover _writing_ archives, though, and whether omitting CRC32s is even allowed by the ZIP format.

FYI, when I tried to sample the ZIP process, it looked like the bounds checks were what slowed things down. It _might_ be faster to directly access the Data's contained bytes instead, see https://github.com/vapor/template-kit/blob/master/Sources/TemplateKit/Utilities/HTMLEscape.swift for an example. However, @weissi strongly recommends _not_ using `unsafe` for purposes like this; maybe he has a suggestion for speeding this up in debug builds without using `unsafe`.

**Comment by MrMage** [comment]
**Update 2:** In case the current `crc32` implementation is kept, here's a way to simplify it in Swift 5 (maybe Swift 4 as well) without a noticeable further loss in performance:

```
#if swift(>=5.0)
		for byte in self {
			let index = Int((result ^ UInt32(byte)) & 0xff)
			result = (result >> 8) ^ crcTable[index]
		}
        #else
```

**Comment by MrMage** [comment]
**Final Update:** The following Swift 5 code yields a ~40% speedup in Release builds and ~10% in Debug builds for me:

```swift
crcTable.withUnsafeBufferPointer { crcTablePointer in
			self.withUnsafeBytes { bufferPointer in
				let bytePointer = bufferPointer.bindMemory(to: UInt8.self)
				for i in 0..<bufferSize {
					let byte = bytePointer[i]
					let index = Int((result ^ UInt32(byte)) & 0xff)
					result = (result >> 8) ^ crcTablePointer[index]
				}
			}
		}
```

Happy to file a PR for this, if you think this is a worthwhile improvement.

My profile of `testPerformanceWriteUncompressed` now looks like this:

<img width="979" alt="Screen Shot 2019-08-22 at 09 37 31" src="https://user-images.githubusercontent.com/117466/63495569-7d82cd80-c4c0-11e9-8f09-7bd50fa74077.png">

No idea why Swift spends so much time initializing integers in Debug builds, though :-/

**Comment by MrMage** [comment]
Also, for my own use of this library, I am simply going to enforce optimizations even in Debug builds through the Podfile:

```ruby
post_install do |installer|
	installer.generated_projects.each do |project|
		project.targets.each do |target|
			# Increase the maximum SQLite variable count.
			if target.name.start_with?('sqlite3')
				target.build_configurations.each do |config|
					config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
					# We need to manually increase the maximum number of SQLite variables to support looong statements
					# (e.g. filtering over a specific set of app activity IDs).
					config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'SQLITE_MAX_VARIABLE_NUMBER=200000000'
				end
			end
			
			# Suppress several warnings.
			if target.name.start_with?('MASShortcut')
				target.build_configurations.each do |config|
					config.build_settings['CLANG_WARN_COMMA'] = 'NO'
				end
			end
			
			if target.name.start_with?('lz4')
				target.build_configurations.each do |config|
					config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
					config.build_settings['CLANG_WARN_COMMA'] = 'NO'
				end
			end

			if target.name.start_with?('libxlsxwriter')
				target.build_configurations.each do |config|
					config.build_settings['CLANG_WARN_STRICT_PROTOTYPES'] = 'NO'
					config.build_settings['GCC_WARN_UNINITIALIZED_AUTOS'] = 'NO'
				end
			end

			if target.name.start_with?('ZIPFoundation')
				target.build_configurations.each do |config|
					config.build_settings['SWIFT_VERSION'] = '5'
					config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
				end
			end
```

**Comment by weissi** [comment]
@MrMage Swift in debug is very slow. You’re really not meant to ever run a debug build for anything but debugging. And debug perf issues won’t get any priority I think.

**Comment by MrMage** [comment]
> @MrMage Swift in debug is very slow. You’re really not meant to ever run a debug build for anything but debugging. And debug perf issues won’t get any priority I think.

I guess that makes sense. I'm simply going to enforce optimizations for ZIPFoundation (even in debug builds) to work around this issue for my project.

**Comment by weichsel** [comment]
> Happy to file a PR for this, if you think this is a worthwhile improvement.

Thank you for looking into this. A PR would be very welcome!

> The following Swift 5 code yields a ~40% speedup in Release builds and ~10% in Debug builds for me. 

That sounds very promising - Looking forward to review the PR.
