### ISSUE TITLE
Unzipping from Data

### ISSUE THREAD

**Issue by adtrevor** [weichsel/ZIPFoundation#142]
Is there a way to unzip from the contents of a `Data` object?

Thank you for this library.

**Comment by weichsel** [comment]
The current shipping version doesn't support processing of archives without file system representation. 
There is an unmerged PR that implements in-memory archives, but it has some technical problems (especially with in-memory writing, which is also part of this PR): https://github.com/weichsel/ZIPFoundation/pull/78
