### ISSUE TITLE
Error when creating large zip file exceeding 4 GB

### ISSUE THREAD

**Issue by Mastergalen** [weichsel/ZIPFoundation#144]
# Summary

Adding entries to zip file exceeding 4.3 GB leads to an error.

# Steps to Reproduce

When creating a zip file and adding new entries with .addEntry() I receive the error `ZIPFoundation.Archive.ArchiveError.invalidStartOfCentralDirectoryOffset` once the file size exceeds around 4.3 GB

# Expected Results

# Actual Results

# Regression & Version

v0.9.9

# Related Link

**Comment by Mastergalen** [comment]
Ah, I see this is due to ZIP64 not being supported #118 

However, the error that is thrown is a bit misleading, perhaps a new error named something like `MaxFilesizeReached` would be more helpful.

**Comment by weichsel** [comment]
Yes ZIP64 is needed for >4GB entries. I will close this issue as it is already tracked in #118.  

Thanks for your input re the error name - will think about a more meaningful name for that error.
