### ISSUE TITLE
Handle when user closes the app while unzipping

### ISSUE THREAD

**Issue by GerardSlash** [weichsel/ZIPFoundation#148]
Hi there,

Just a quick question: 

Is there any way to handle when the user closes the app while unzipping a file?
Because I've tried to close the app while unzipping a file, and the unzipped folder is created, but it is not completely processed (corrupted), so I would want to know if there is a way to handle this, like deleting the file that it's unzipping when the user closes the app, or some workaround. 

Thanks.

**Comment by weichsel** [comment]
You could call the `Progress` API which exposes a `cancel()` method in your app delegate's `applicationWillTerminate` implementation. After cancelation you will have to clean up - e.g. by removing any incomplete destination folders. You can learn more about progress tracking/cancelation [here](https://github.com/weichsel/ZIPFoundation#progress-tracking-and-cancellation):

**Comment by GerardSlash** [comment]
Thanks @weichsel !

I'll take a look!
