### ISSUE TITLE
Access to Archive(data: ...) in SwiftPM project

### ISSUE THREAD

**Issue by daSkier** [weichsel/ZIPFoundation#150]
Hi, I'm trying to use the (new?) `Archive(data: accessMode: preferredEncoding: )` function in a SPM project, but this init function does't seem available. 

I know this function is Swift 5 only, so is there something special I need to be doing in my `Package.swift` to ensure Swift 5 compilation for the Swift 5 specific function? I already included `swiftLanguageVersions: [SwiftVersion.v5]`, but that didn't seem to work.

This is the current `Package.swift`:
```Swift
// swift-tools-version:5.1
import PackageDescription

let package = Package(
    name: "PSVaporV4",
    platforms: [
       .macOS(.v10_14)
    ],
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "4.0.0-beta"),
        .package(url: "https://github.com/vapor/fluent.git", from: "4.0.0-beta"),
        .package(url: "https://github.com/vapor/fluent-postgres-driver.git", from: "2.0.0-beta"),
        .package(url: "https://github.com/weichsel/ZIPFoundation.git", from: "0.9.10")
    ],
       targets: [
        .target(name: "App", dependencies: [
            "Fluent", 
            "FluentPostgresDriver",
            "Vapor",
            "ZIPFoundation"
        ]),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App", "XCTVapor"])
    ],
       swiftLanguageVersions: [SwiftVersion.v5]
)
```

Thanks for any help you can provide on the subject.

**Comment by weichsel** [comment]
Hi, 

this feature is brand new, so we haven't tagged a release version yet. 
If you want to test it, you'll have to point your dependency package to the `development` branch:
```swift
.package(url: "https://github.com/weichsel/ZIPFoundation.git", .branch("development"))
```

**Comment by daSkier** [comment]
@weichsel Ah, awesome. Thanks for the info. I'll work on integrating the package in that way to test it out. 

Since this is new functionality do you have a way you envision this in memory decompression to be used or any sample code? 

I'm trying to download and decompress a zip in memory on a server and then turn around and re-upload the decompressed data to S3. The only way I can see to do this is with the consumer method `extract(_ entry: Entry, bufferSize: UInt32 = defaultReadChunkSize, skipCRC32: Bool = false, progress: Progress? = nil, consumer: Consumer) throws -> CRC32` and assembling the Data chunks. Or, is there a convenience method for this that I've missed?

**Comment by weichsel** [comment]
For file-backed archives we have convenience methods to extract on a per-file basis.  
If you want to avoid all file system round trips, you'll have to use `Archive(data: ...)` in combination with `extract(..., consumer: {})`.
