### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by mattneub** [weichsel/ZIPFoundation#151]
I think most people think that "zip" means "compress". Therefore, showing in the documentation that the command to zip something is

    try fileManager.zipItem(at: sourceURL, to: destinationURL)

does no one any favors, because the user is surprised to discover that the destination file is larger than the original. Turns out you have to specify the compression method `.deflate` if you want to save any space. Okay, cool, but then wouldn't it be nice to mention that on the README somewhere? Thanks!

**Comment by weichsel** [comment]
Thanks for your input Matt. 
I added a short section about the default compression behavior to the README and also to the doc strings of all methods that expose a `compressionMethod` parameter.

**Comment by mattneub** [comment]
That looks great, thanks! This will save a lot of people from stubbing their toes. :)
