### ISSUE TITLE
In memory archive with ZipFoundation

### ISSUE THREAD

**Issue by Borko4vp** [weichsel/ZIPFoundation#157]
As stated in the github [doc](https://github.com/weichsel/ZIPFoundation#in-memory-archives), it should be possible to create in memory archive, still I am unable to find appropriate init method of the Archive class. Am i doing something wrong or this is not yet released?

I have seen the [PR](https://github.com/weichsel/ZIPFoundation/pull/143) but still i cant see why this is in the documentation on the github page.

When will this feature be released?

**Comment by weichsel** [comment]
Hi,

The GitHub project page shows the state of `README.md` in the development branch (which is the default branch of the project).  
The feature is very new and there is no tagged release yet.  
If you want to use/test in-memory archives, please point your package manager to `development`.  

Please also note that this feature is also only available if you are targeting Swift 5 or newer. If you are integrating via Carthage, you will have to manually set the `SWIFT_VERSION` of the ZIPFoundation.xcodeproj to `5` manually. It is currently set to `4` for compatibility reasons. (Carthage does not provide a way to specify the language version).

**Comment by Borko4vp** [comment]
Great thank you for the info.
