### ISSUE TITLE
Issues with swift 5.2

### ISSUE THREAD

**Issue by pankajsoni19** [weichsel/ZIPFoundation#161]
Just compiled it with 5.2, seems to have some leaks, dangling pointers, etc. I saw from your commit that you have ironed those out. Could you release the package soon?

**Comment by bigyelow** [comment]
+1. When can we publish a new version containing this https://github.com/weichsel/ZIPFoundation/pull/159?

**Comment by weichsel** [comment]
Released 🎉

**Comment by bigyelow** [comment]
Great thanks!
