### ISSUE TITLE
march 27 2020 Xcode warning Initialization of 'UnsafeBufferPointer<UInt32>' results in a dangling buffer pointer

### ISSUE THREAD

**Issue by ingconti** [weichsel/ZIPFoundation#164]
# Summary

using Version 11.4 (11E146) I got a warning not present in previous versions.

# Steps to Reproduce

download last Xcode and rebuild.

# Expected Results

no warnings.
# Actual Results

        var data = Data(buffer: UnsafeBufferPointer(start: &localFileHeaderSignature, count: 1))
msg:
Initialization of 'UnsafeBufferPointer<UInt32>' results in a dangling buffer pointer
# Regression & Version

# Related Link

**Comment by weichsel** [comment]
Have you already updated to the recently released version 0.9.11 of ZIPFoundation? Those errors should be gone.

**Comment by ingconti** [comment]
glad to hear so!
