### ISSUE TITLE
Failed to unzip an unencrypted .epub eBook

### ISSUE THREAD

**Issue by cjm3** [weichsel/ZIPFoundation#165]
# Summary
An epub ebook is the zipped contents of a directory which contain files and other directories. One entity is a directory called "META-INF". ZIPFoundation fails to see that this is a directory and creates a file of the same name in the output directory. Then an error is thrown. Extraction of ZIP archive failed with error:Error Domain=NSCocoaErrorDomain Code=516 "The file “META-INF” couldn’t be saved in the folder “directory” because a file with the same name already exists." On debug I saw that Entry.swift line 146 was never called and the only lines 144 and 150 were called. Also the var isDirectory was set to true even though it was not used since the .msdos case was never called.

# Steps to Reproduce
Try to unzip an unencrypted epub ebook.

# Expected Results
The unzipped contents of the epub ebook to be unzipped with the same directory structure as the original epub.

# Actual Results
Same as described in Summary.

# Regression & Version

# Related Link

**Comment by weichsel** [comment]
Hi,

Thank you for your bug report.  
I tried to reproduce the problem with a sample .epub file from the Adobe sample library.  
Extracting this [EPUB version of "Alice in Wonderland"](https://contentserver.adobe.com/store/books/aliceDynamic.epub) worked for me - including the `META-INF`  directory and its contents.  

I used the `unzipItem(...)` convenience method of `FileManager` that comes with ZIP Foundation.   
```swift
if let url = Bundle.main.url(forResource: "aliceDynamic", withExtension: "epub") {
    let fileManager = FileManager()
    let tempURL = URL(fileURLWithPath: NSTemporaryDirectory()).appendingPathComponent(ProcessInfo.processInfo.globallyUniqueString, isDirectory: true)
    try? fileManager.unzipItem(at: url, to: tempURL)
    print(tempURL)
}
```

Can you investigate (or attach) the .epub file you are trying to extract. And also the code you are using for the extraction.

**Comment by cjm3** [comment]
Hi,





let fileManager = FileManager()
let currentWorkingPath = "/Users/barnaby/Projects/Xcode/MacOS/eBook2/“
var sourceURL = URL(fileURLWithPath: currentWorkingPath)
//sourceURL.appendPathComponent("aliceDynamic.epub”)					// works
sourceURL.appendPathComponent("JaneAusten-Pride&Prejudice.epub”)		// doesn’t work
var destinationURL = URL(fileURLWithPath: currentWorkingPath)
destinationURL.appendPathComponent("directory")
do {
	try fileManager.createDirectory(at: destinationURL, withIntermediateDirectories: true, attributes: nil)
	try fileManager.unzipItem(at: sourceURL, to: destinationURL)
} catch {
	 print("Extraction of ZIP archive failed with error:\(error)")
}



Thanks for getting back to me.  I downloaded the Alice in Wonderland book you used and it did work perfectly.  I’m attaching one of the ones I had errors with.  I’ve unzipped these books with “The Unarchiver.app” and they both unzip correctly with that and I have opened both books with Apple’s “Books.app” without problems.  I don’t know, maybe I have some sort of file permission issue going on in Xcode even though I don’t have any sandboxing enabled.  I don’t want to waste your time on this.  I’m just doing a personal hobby type app to organize my ebooks so it’s not a big deal.

Chris




On Apr 5, 2020, at 4:20 AM, Thomas Zoechling <notifications@github.com> wrote:


Hi,

Thank you for your bug report.
I tried to reproduce the problem with a sample .epub file from the Adobe sample library.
Extracting this EPUB version of "Alice in Wonderland" <https://contentserver.adobe.com/store/books/aliceDynamic.epub> worked for me - including the META-INF directory and its contents.

I used the unzipItem(...) convenience method of FileManager that comes with ZIP Foundation.

if let url = Bundle.main.url(forResource: "aliceDynamic", withExtension: "epub") {
    let fileManager = FileManager()
    let tempURL = URL(fileURLWithPath: NSTemporaryDirectory()).appendingPathComponent(ProcessInfo.processInfo.globallyUniqueString, isDirectory: true)
    try? fileManager.unzipItem(at: url, to: tempURL)
    print(tempURL)
}
Can you investigate (or attach) the .epub file you are trying to extract. And also the code you are using for the extraction.

**Comment by weichsel** [comment]
Hi Chris,

The "JaneAusten-Pride&Prejudice.epub” attachment is missing. I assume you replied via mail. It seems GitHub is not adding mail attachments to an issue. You can attach the .epub by replying via GitHub web interface and dragging a zipped version of the .epub into the reply textfield.

**Comment by cjm3** [comment]
Ok. Hopefully this works and also that a zip of a zip doesn't cause problems.


[JaneAusten-Pride&Prejudice.epub.zip](https://github.com/weichsel/ZIPFoundation/files/4434140/JaneAusten-Pride.Prejudice.epub.zip)

**Comment by cjm3** [comment]
Should have though of this sooner...  I unzipped the epub giving me a problem and then zipped  the top level directory that was extracted using the MacOS compress right click file menu in finder.  That ZIPFoundation decompresses that without error and it calls line 146 in Entity.swift so it now sees that there are directories inside the top level directory in the compressed zip file.  So it seems my files are a different zip format. I don't know what. I'll see if I can find out. Again, this is not important so you don't have to use your time up on this issue.

**Comment by cjm3** [comment]
Just saw that ZIPFoundations creates an extra directory "__MACOSX" at the same level as the uncompressed top level epub directory.  It contains the directory's of the epub but no data files. This doesn't happen when I unzip it with "The Unarchiver.app". So something extra is going on.

**Comment by weichsel** [comment]
I just looked into the file you sent me and to me it looks like that the ZIP metadata in this file is invalid. I was also not able to extract it with the default macOS Archive utility.  

The attributes of the `META-INF/` entry in the archive lack information about what kind of entry that path represents. ZIP Foundation supports `.directory`, `.file` and `.symlink`. Usually the program/library that creates the archive should store that kind of information. This seems to be not the case here.  

I was able to open the file with Books.app. So probably some epub apps are fault tolerant and skip content if it can't be extracted. You could also do that in your project by using a lower level approach (= not using the `FileManager` extension):  
Iterate over all entries in an archive and then use the `Archive.extract(...)` method to extract an entry. If you encounter `META-INF` skip it.  

Is the .epub you provided a public file from a 3rd party or do you have control over how this is created. If the latter is the case, you might be able to fix the bug there. I am pretty sure that the way the `META-INF` directory entry is written is not conforming to the ZIP specification.  

Regarding the `__MACOSX` directory: This is a "feature" of macOS: https://superuser.com/questions/104500/what-is-macosx-folder
As this is a regular directory (just hidden), ZIP Foundation includes it when creating an archive and also extracts it during unzip. The Unarchiver might have an option to ignore that special path (which is usually what you want as a user).

**Comment by cjm3** [comment]
Thanks for looking into this.  The epub was downloaded from the Project Gutenberg site so I don't have any control over creating them.  I think I'll find some way to automate unzipping them and then use ZIPFoundation to re-zip them.  Then they will be correct.  Thanks again for looking into this.  I guess I hit the "Close and comment" button know to close the issue?
