### ISSUE TITLE
Password Protection for created Zip file

### ISSUE THREAD

**Issue by Vaishumatha** [weichsel/ZIPFoundation#166]
**Is your feature request related to a problem? Please describe.**
Providing password protection for created zip file - GDPR.

**Describe the solution you'd like**
Option to provide password if needed during the creation of zip.

**Describe alternatives you've considered**
Alternative is to create the zip, and then in my project adding the code to password protect the zip file.

**Comment by weichsel** [comment]
Duplicate of #25
