### ISSUE TITLE
How to read only part of an entry?

### ISSUE THREAD

**Issue by mickael-menu** [weichsel/ZIPFoundation#167]
First of all, thank you for the great work you put in this library!

I'd like to completely ditch minizip in favor of ZIPFoundation, but there's one use case that I'm not sure how to handle with ZIPFoundation. Basically, I need to extract only a portion of length _n_ of a compressed file, at a particular offset _i_. The use case is serving the entry over an HTTP byte-range request, which should not be entirely loaded into memory.

I didn't find any way to do it in the API, but it looks like it should be possible by exposing a few functions. Did I miss something?

I'd be happy to contribute a pull request if that's something you're interested in.

Thanks again

**Comment by weichsel** [comment]
Hi Mickael,

If I understand correctly, you are running a server-side Swift process that accepts HTTP requests.  
If you get an HTTP range request, you want to "mount" a ZIP archive and serve a specific entry which is located at the start of the requested range.  

How do you get the byte-range for the request on the client? 
Does the range span the entire ZIP entry, or does it only contain the data section of the entry?  
If the latter is the case you could use the `decompress` method in the `Data+Compression` extension.  
If the range contains the "full" ZIP entry (= header(s) + payload) and you need to parse that entry on the server to find the actual payload, you will have to build a data structure first that allows offset→entry lookups. By default, entries can only be found via `path`.  

The framework intentionally hides most of the offset/range handling so you'll have to expose the `dataOffset` property of `Entry`. (Maybe you can use `@testable import ZIPFoundation` to experiment without modifying the framework code)
With `dataOffset` exposed you could build an offset→entry lookup dictionary like that:   
```swift
let offsetLookup = archive.reduce(into: [Int: Entry]()) { $0[$1.dataOffset] = $1 }
```

I want to avoid to expose too many implementation details of archives/entries but if I understand your use case better, we can probably find a way to provide the needed metadata in an encapsulated way.

**Comment by mickael-menu** [comment]
Thank you for your quick answer.

To give you more details, the context is an [open source EPUB reader](https://github.com/readium/r2-navigator-swift). EPUB is basically a collection of HTML files in a ZIP archive, but they can also contain additional resources such as video clips.

These are the initialization steps we're following:
1. Open/mount the EPUB/ZIP archive.
2. Start an internal HTTP server to serve the ZIP entries.
3. Present the HTML entries through a `WKWebView`.

If the `WKWebView` encounters a video clip in an HTML document, then it will emit HTTP byte-range requests to stream the video. We're supposed to answer these requests in our internal server. In this case, we would like to be able to read a specific (random) range of the ZIP entry corresponding to the video clip.

Because these videos can be quite large, we don't want to load the full content in memory. Also, the user should be able to skip ahead during playback, so we're not always reading the ZIP entry from offset 0.

> Does the range span the entire ZIP entry, or does it only contain the data section of the entry?

I'm not sure I fully understand the difference, but when receiving the byte-range request, we only care about the data of the entry itself. We might need the uncompressed size, but it will be requested and cached earlier.

> If the latter is the case you could use the decompress method in the Data+Compression extension.

I guess I would need to have access to `Data.readChunk` and the `archiveFile` handle as well to use `decompress()`? Or do you mean that I should open an additional file handle to handle this?

> The framework intentionally hides most of the offset/range handling so you'll have to expose the dataOffset property of Entry. 

Yes, I can sympathize with the need to keep the API straightforward.

I think that adding a single `range: Range<UInt32>?` parameter (bound to `0..<uncompressedSize`) in the `extract` functions would fit this use case without making the API too complicated.

**Comment by weichsel** [comment]
Thanks for the detailed explanation of your use case - Readium looks like an interesting project! 

> If the WKWebView encounters a video clip in an HTML document, then it will emit HTTP byte-range requests to stream the video. We're supposed to answer these requests in our internal server. In this case, we would like to be able to read a specific (random) range of the ZIP entry corresponding to the video clip.  

I think this will be impossible to accomplish, because `deflate` (which is the most commonly used compression algorithm for ZIP files) is stream-based and does _not_ support random access. There are ways to [make `deflate` compressed data indexable]([url](https://stackoverflow.com/a/31275306/100848)), but this requires to read the whole entry at least once. In your initial post you mentioned that you are currently using minizip to decompress the entry. Did you find a way to index into an entry with minizip? I assume this also requires seeking into the data with O(N) time complexity. 

I think the best you could do is to use the closure based ZIP Foundation API and read chunks with the passed in consumer closure until you reach your offset - dropping anything before.  
This will allow you to seek to the requested byte range with linear time and constant space complexity.

**Comment by mickael-menu** [comment]
> Did you find a way to index into an entry with minizip? I assume this also requires seeking into the data with O(N) time complexity.

Unfortunately no, and you actually just answered a TODO that was in the project 👍 
```
// TODO: Check if you can seek directly to offset in minizip instead of reading the bytes
```

> I think the best you could do is to use the closure based ZIP Foundation API and read chunks with the passed in consumer closure until you reach your offset - dropping anything before.

Seems like the way to go indeed. I guess that I need to use `Progress` to cancel the extraction once the range is reached.

Thank you!
