### ISSUE TITLE
Please update this line to 'return isDirectory ? .directory : .file'

### ISSUE THREAD

**Issue by dinodev90** [weichsel/ZIPFoundation#170]
https://github.com/weichsel/ZIPFoundation/blob/ec32d62d412578542c0ffb7a6ce34d3e64b43b94/Sources/ZIPFoundation/Entry.swift#L150

**Comment by weichsel** [comment]
Guessing the entry type based on the path suffix shouldn't be necessary on UNIX based platforms. Did you encounter an archive that has no `mode` set for an entry that actually is a directory? If yes, can you please check to what value `let mode = mode_t(self.centralDirectoryStructure.externalFileAttributes >> 16) & S_IFMT` expands to? 
Maybe we should handle that case as well.

**Comment by dinodev90** [comment]
Here are the values I am getting while extracting and getting 0 for `mode`

`self.centralDirectoryStructure.externalFileAttributes` = 27525120

`mode_t(self.centralDirectoryStructure.externalFileAttributes >> 16)` = 420

`S_IFMT` = 61440

`mode_t(self.centralDirectoryStructure.externalFileAttributes >> 16) & S_IFMT` = 0

**Comment by weichsel** [comment]
Do you have a sample archive?

**Comment by dinodev90** [comment]
[test_archive.zip](https://github.com/weichsel/ZIPFoundation/files/4809975/test_archive.zip)

**Comment by weichsel** [comment]
Thank you!

**Comment by GRiMe2D** [comment]
I found a little EPUB today and made a pull request.
