### ISSUE TITLE
Help to understand how to zip a directory that contains symbolic links

### ISSUE THREAD

**Issue by fenixkim** [weichsel/ZIPFoundation#174]
I'm new in Swift.

I'm creating a directory in a temporary path, within I adding some symlinks of large files (~600mb).

When I zip the directory using the `fileManager.zipItem` function the archive is created but the symlinks were not resolved, I'm getting a very smaller file instead. It seems is compressing the symlink instead of the linked large file.

Is this normal behavior? or I'm doing something wrong.

I appreciate any help. 

Thanks in advance

**Comment by weichsel** [comment]
Hi Alexander,

The ZIP file format does have a dedicated entry type for symlinks and therefore does preserve symlinks. A symlink is added to the archive "as-is" without prior resolution.  
If the file that the symlink points to is not part of the archive, the link might be not resolvable after extraction.  

Th `zipItem` method does not automatically resolve the link. If you want to add the underlying data to the archive, you will have to resolve the symlink and use lower level methods (such as `Archive.addEntry`) to build your archive.

**Comment by fenixkim** [comment]
Ok, thanks for your quick reply.

The idea of using symlink becomes from the need to customize the name of the item into the archive. Some times I want to compress some large file, but I want a different name on the archive, so I don't need to duplicate the file and change its name, then delete it. 

So I thought... "I'm going to create a symlink in order to customize its name." :/

Do you have any idea of how to change the name of the file into the Archive?

Thanks

**Comment by weichsel** [comment]
To use a custom name for an entry, you can either rename the file in your source directory (if this is possible for your use case), or you can use the closure-based version of `addEntry... provider: Provider`. When using the latter, you can use any name for the `path` paramter (e.g. parameter: `addEntry(with: "custom.name"`) and implement a `Provider` closure that reads from the file on your local file system.

**Comment by fenixkim** [comment]
I did something like this:

```swift
extension Archive {
    
    /// Adds a entry of type file only which has the posibility to sets a name for the file
    /// - Parameters:
    ///   - url: The entry URL
    ///   - fileName: The entry custom name
    ///   - compressionMethod: Indicates the CompressionMethod that should be applied to Entry. By default, no compression will be applied.
    ///   - bufferSize: The maximum size of the write buffer and the compression buffer (if needed).
    ///   - progress: A progress object that can be used to track or cancel the add operation.
    /// - Throws: An error if the source file cannot be read, the receiver is not writable or the entry is not a regular file
    public func addEntry(
        withURL url: URL,
        fileName: String,
        compressionMethod: CompressionMethod = .none,
        bufferSize: UInt32 = defaultWriteChunkSize,
        progress: Progress? = nil
    ) throws {
        
        // Resource values
        let rv = try url.resourceValues(forKeys: [
            .fileSizeKey,
            .totalFileSizeKey,
            .contentModificationDateKey,
            .isRegularFileKey
        ])
        
        guard rv.isRegularFile! else {
            throw CocoaError(.fileReadInvalidFileName)
        }
        
        let fileManager = FileManager()
        
        guard fileManager.itemExists(at: url) else {
            throw CocoaError(.fileReadNoSuchFile, userInfo: [NSFilePathErrorKey: url.path])
        }
        
        let modDate = rv.contentModificationDate!
        let uncompressedSize = UInt32(rv.fileSize ?? rv.totalFileSize ?? 0)
        let permissions = try FileManager.permissionsForItem(at: url)
        let entryFileSystemRepresentation = fileManager.fileSystemRepresentation(withPath: url.path)
        
        /// The fileName + url path extension. ei: file.psd
        var entryName = "\(fileName).\(url.pathExtension)"
        
        // Checks unique name
        var counter: UInt = 2
        while self[entryName] != nil {
            entryName = "\(fileName)-\(counter).\(url.pathExtension)"
            counter += 1
        }
        
        guard let entryFile: UnsafeMutablePointer<FILE> = fopen(entryFileSystemRepresentation, "rb") else {
            throw CocoaError(.fileNoSuchFile)
        }
        
        defer { fclose(entryFile) }
        
        try self.addEntry(
            with: entryName, type: .file, uncompressedSize: uncompressedSize,
            modificationDate: modDate, permissions: permissions,
            compressionMethod: compressionMethod, bufferSize: bufferSize,
            progress: progress, provider: { _, _ in
                try Data.readChunk(of: Int(bufferSize), from: entryFile)
        })
    }
}
```

But, I suffered a lot with the very useful functions you have like: `fileManager.itemExists(at:)`, `FileManager.permissionsForItem(at: url)` and `Data.readChunk` due to class access restrictions. It should be great that an `addEntry` with a custom name parameter were official here.

Please forgive me if I'm doing it wrong, I'm very new to Swift. But it worked very well for me for now.

**Comment by weichsel** [comment]
The existing set of API does currently not provide convenience methods for all use cases. 
It is separated in 3 "level":
 - very high level: The `FileManager` extensions like `zipItem`.
 - intermediate level: `Archive` and `addEntry` with the relative path parameter. 
 - low level: `Archive` and with the `Provider`& `Consumer` closure based API

IMO providing convenience methods for a lot of different use cases would make the API very overwhelming.  
We settled on the 3-tier approach above, where the low-level tier provides a lot of flexibility.

**Comment by fenixkim** [comment]
Ok, I understand.

Thanks a lot for your support.
