### ISSUE TITLE
Archive of single file has 0 Entries

### ISSUE THREAD

**Issue by skhillon** [weichsel/ZIPFoundation#175]
Thank you for making this library in Swift!

I'm having some trouble downloading a zip file from my backend and unzipping it on-device. The archive `data.zip` has only 1 JSON file, `data.json`.

**However, my archive is empty.**
```swift
(lldb) po archive.reversed()
0 elements
```

I created a 50-line example [at this repository](https://github.com/skhillon/UncompressTesting/blob/master/UncompressTesting/ViewController.swift#L33). The main issue is the guard statement being entered:

<img width="640" alt="Screen Shot 2020-06-22 at 2 24 00 AM" src="https://user-images.githubusercontent.com/8892223/85271288-7190d080-b42f-11ea-9381-af6c2a6efa1f.png">

I would appreciate any help in figuring out why my `Archive` object is empty.

**Comment by skhillon** [comment]
@weichsel Hope this didn't get buried! I pasted the code below. Do you see any reason why the archive would have 0 entries?

```swift
guard let url = Bundle.main.url(forResource: "data", withExtension: "zip") else {
  return
}

// Load archive file contents as `Data`, which is the same thing you would get from the server.
guard let fileData = try? Data(contentsOf: url, options: .uncached) else {
  return
}

guard let archive = Archive(data: fileData, accessMode: .create) else {
  return
}

// The archive should have just 1 file, which we want to extract.
guard let entry = archive["data.json"] else {
  // === ERROR: This guard block is entered. ===
  return
}

do {
  // Combine all chunks into one, which can then be JSON serialized.
  var uncompressedData = Data()
  _ = try archive.extract(entry) { chunk in uncompressedData.append(chunk) }

  // Convert to JSON and print to make sure it looks ok.
  let json = try JSONSerialization.jsonObject(with: uncompressedData, options: []) as? [String: Any]
  print(json as Any)
} catch {
  print("Extracting entry from archive failed with error:\(error)")
}
```

**Comment by weichsel** [comment]
Hi,

You are using the wrong `accessMode` when initializing the archive.  
You should use `.read` here. `.create` initializes a _new_ archive without any content.

**Comment by skhillon** [comment]
Ah I see. I thought for some reason that, because this was happening in-memory, I would need to create a temporary buffer

That works! Thank you

**Comment by weichsel** [comment]
Glad I could help!
