### ISSUE TITLE
Unzip Performance

### ISSUE THREAD

**Issue by bensLine** [weichsel/ZIPFoundation#177]
# Summary
I have to unzip ~20MB files and had the impression that the process took quite long. Hence, I did a comparison with [Zip](https://github.com/marmelroy/Zip) and the results diverged much more than expected. ~30s with ZIPFoundation and only 0.4s with Zip.
![performace tests](https://user-images.githubusercontent.com/5795552/86132328-060dc980-bae7-11ea-9c9b-39c60f1511cc.png)
Not sure what's causing the issue or if there is a mistake in my test. 

# Steps to Reproduce
I cannot provide the zip file I used but it has many subdirectories and files:
<img width="611" alt="zip structure" src="https://user-images.githubusercontent.com/5795552/86133060-15414700-bae8-11ea-97ae-74354aebfef3.png">

<details>
  <summary>Test Code</summary>
  
```
import Foundation
import XCTest
import Zip

class ZipTests: XCTestCase {
	private let tempUrl = FileManager.default.temporaryDirectory.appendingPathComponent("zip-test")

	private var zipUrl: URL {
		Bundle(for: Self.self).url(forResource: "file", withExtension: "zip")!
	}

	override func setUp() {
		super.setUp()
		try? FileManager.default.removeItem(at: tempUrl)
	}

	func test_zip_performanceWithProgress() {
		measure {
			do {
				try Zip.unzipFile(zipUrl, destination: tempUrl, overwrite: true, password: nil, progress: { _ in }) { _ in }
				try FileManager.default.removeItem(at: tempUrl)
			} catch {
				fail("\(error)")
			}
		}
	}

	func test_zipFoundation_performanceWithProgress() {
		measure {
			let p = Progress()
			do {
				try FileManager.default.unzipItem(at: zipUrl, to: tempUrl, progress: p)
				try FileManager.default.removeItem(at: tempUrl)
			} catch {
				fail("\(error)")
			}
		}
	}

	func test_zip_performance() {
		measure {
			do {
				try Zip.unzipFile(zipUrl, destination: tempUrl, overwrite: false, password: nil, progress: nil) { _ in }
				try FileManager.default.removeItem(at: tempUrl)
			} catch {
				fail("\(error)")
			}
		}
	}

	func test_zipFoundation_performancea() {
		measure {
			do {
				try FileManager.default.unzipItem(at: zipUrl, to: tempUrl)
				try FileManager.default.removeItem(at: tempUrl)
			} catch {
				fail("\(error)")
			}
		}
	}
}
```
</details>

# Expected Results
Unzip performs significantly faster <1s

# Actual Results
Unzipping takes ~30s

# Regression & Version
SPM 0.9.11, Xcode 11.5

**Comment by weichsel** [comment]
Hi, 

Thank you for providing the detailed test cases and your performance measurements.  

I don't know about the internals of `Zip`, but some Swift ZIP frameworks are wrappers around C implementations of the ZIP format (like e.g. minizip). 
ZIP Foundation is a pure Swift implementation and it therefore is prone to the large performance discrepancy between `DEBUG` and `RELEASE` builds in Xcode.  
Can you please try to re-run your measurements with the "Test" run configuration set to "Release". (cmd+opt+u, "Test", "Build Configuration: Release"). I'd expect the results to improve drastically for the ZIP Foundation based test cases.

**Comment by bensLine** [comment]
Ahh! I see, that did the trick. Thanks for the clarification 👍 
![image](https://user-images.githubusercontent.com/5795552/86215391-d1e4e800-bb7c-11ea-98dc-028bfb2339cd.png)
