### ISSUE TITLE
Cannot find entries in large file (5Gb)

### ISSUE THREAD

**Issue by luhahaha** [weichsel/ZIPFoundation#178]
I'm trying to find a specific entry in a zip file with size 5Gb.

I have tried to go through all the entries with a `for` and I also have tried open the specific entry with its path. 
But seems that in both cases nothing is found.

Code with for:
```
let archiveURL = URL(string: url)
guard let archive = Archive(url: archiveURL!, accessMode: .read) else {
   return reject("archive_error","Cannot open archive", nil)
}
for entry in archive {
    let path = entry.path;
    if path.contains("inbox/message"){
       return "found"
    }
}
```

Code for specific entry:
```
if let entry = archive["inbox/message/index.html"] {
   return "found"
}
```

**Comment by weichsel** [comment]
ZIP Foundation does currently not support [ZIP64](https://en.wikipedia.org/wiki/Zip_(file_format)#ZIP64). Hence, neither archives nor entries with a file size over 4GB are supported.

**Comment by aehlke** [comment]
(zipfoundation appears to support zip64 now, for those finding this old issue)
