### ISSUE TITLE
Sequence.first(where:) may improve performance for Archive.subscript()

### ISSUE THREAD

**Issue by stevehartwell** [weichsel/ZIPFoundation#181]
In the `Archive.subscript()` method, you may prefer to implement it with `.first(where:)`, which will be on average twice as fast as `.filter()`:
https://github.com/weichsel/ZIPFoundation/blob/6611cfcf4343756661ba9d396b2a26ac2a87971d/Sources/ZIPFoundation/Archive.swift#L231
 
Nice project, by the way.  Very catchy name for it, too. :-)

**Comment by weichsel** [comment]
Nice catch - thanks for pointing that out.
