### ISSUE TITLE
Hi, can't use the framework in an Obj-C command-line tool - can't compile.

### ISSUE THREAD

**Issue by Motti-Shneor** [weichsel/ZIPFoundation#184]
Hi, and thanks for this gleaming framework. Unfortunately I'm working on an old Obj-C codebase, and need to integrate your framework in it. 

So... old style... I dragged the ZIPFoundation project reference into mine, made sure it builds and tests well - then added the ZipFoundation framework target as dependency to mine, and linked against its product - all builds well.

Now comes the source part...
I quickly translated one of the suggested "Advanced API usage examples from the repo wiki (see below) 

but the "Archive" and "Entry" classes seem to be unavailable to my code (compiler error: Use of undeclared identifier 'Archive'). What's wrong? the module IS created and exported, and I'm able to link against it.  What's missing, and can I fix it myself?

Please advise.
```
#import <Foundation/Foundation.h>
#import <ZIPFoundation/ZIPFoundation-Swift.h>
int main(int argc, const char * argv[]) {
    @autoreleasepool {
        NSFileManager *fileManager = [NSFileManager defaultManager];
        NSString *currentWorkingPath = [fileManager currentDirectoryPath];
        NSURL *archiveURL = [NSURL fileURLWithPath: currentWorkingPath];
        archiveURL = [archiveURL URLByAppendingPathComponent:@"DocLabel.docx"];
        Archive *archive = [[Archive alloc] initWithURL:archiveURL accessMode: read ];
        if (archive == nil)
            return;

        Entry *entry = archive["DocProps/custom.xml"];
        if (entry == nil)
            return;

        NSURL *destinationURL = [[NSURL fileURLWithPath: currentWorkingPath] URLByAppendingPathComponent:"labels.xml"];
        
        @try {
            [archive extract:entry to:destinationURL];
        } @catch (NSException *exception) {
            NSLog(@"Exception occured: %@", exception);
        } @finally {
            NSLog(@"Finally...");
        }
    }
    return 0;
}

```

**Comment by Motti-Shneor** [comment]
The generated header file does not seem to include any of your public classes, types etc. I can attach it here if necessary

**Comment by weichsel** [comment]
Hi,

We don't support Objective-C out of the box, but you should be able to wrap functionality you need by creating a Swift wrapper class within your project and then expose that class to Obj-C.

```swift
import Foundation
import ZIPFoundation

@objc
class ZIPWrapper: NSObject {

    @objc
    func extract() -> Bool {
        let archive = Archive(accessMode: .read)
        // ...
        // return true
    }
}
```

you can then use that class from Obj-C like that

```objc
ZIPWrapper *wrapper = [[ZIPWrapper alloc] init];
[wrapper extract];
```

**Comment by Motti-Shneor** [comment]
Thank you! I have already started looking at your code and see what needs to be done to @objc the classes and enumerators and basic functionality... but it seems lots of work is due. Do you consider investing in it? there are plenty of important projects that are pure Obj-C out there

BTW do you know of any Obj-C Framework repository that wraps around zip archives in a similar way to yours? Zip Foundation is really beautiful - but Obj-C still exists...

**Comment by weichsel** [comment]
> Do you consider investing in it? there are plenty of important projects that are pure Obj-C out there

No. We want to focus on Swift-only for now. This allows us to freely use Swift language features in the API and it also allows us to reach platforms (e.g. Linux) that would be harder to target if we bring in Obj-C.

> BTW do you know of any Obj-C Framework repository that wraps around zip archives in a similar way to yours? Zip Foundation is really beautiful - but Obj-C still exists...

I haven't used it myself but I have heard good things about ZipZap: https://github.com/pixelglow/ZipZap
