### ISSUE TITLE
Could not find module 'ZIPFoundation' for target 'arm64-apple-ios-simulator'

### ISSUE THREAD

**Issue by 1agora** [weichsel/ZIPFoundation#189]
# Summary
Error: Could not find module 'ZIPFoundation' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64

using SPM to install library

# Steps to Reproduce
build for simulator using xcode 12

# Expected Results
build successfully

# Actual Results
Error: Could not find module 'ZIPFoundation' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64

# Regression & Version

# Related Link

**Comment by weichsel** [comment]
Are you building via Xcode or on the command line?  
If you are using Xcode, which version?  
I tried to to build a test project that integrates ZIPFoundation via SPM with Xcode 12.2 Beta 3 - Project built and ran without errors.

**Comment by 1agora** [comment]
xcode 12.0
building through xcode
and solution was to set "build active architectures only" to YES.

**Comment by zinwalin** [comment]
> xcode 12.0
> building through xcode
> and solution was to set "build active architectures only" to YES.

set YES in main project or Pods project settings?
