### ISSUE TITLE
Swift 3.x compatibility

### ISSUE THREAD

**Issue by akbsteam** [weichsel/ZIPFoundation#19]
Is there a blocking issue with swift 3 compatibility? With a few minor changes, it seems to compile ... 
(just casting a few Uint32 to Int for comparison)

**Comment by weichsel** [comment]
I recently had to close a Pull Request (#16) that tried to make the project usable with Swift 3. The proposed changes broke the test suite and also violated some aspects of the ZIP specification.  
I currently plan to reach 1.0 as soon as the final versions of Swift 4/Xcode 9 get released with Swift 4 as the minimum language target but you should be able to get a Swift 3 compatible fork by implementing the things I commented in closed PR.
