### ISSUE TITLE
Check for zip64 is incorrect

### ISSUE THREAD

**Issue by OCJvanDijk** [weichsel/ZIPFoundation#195]
Hi and happy new year!

A while ago I opened PR #169, time went by after that and I forgot exactly what was going on. I ran into this problem again and this time I will write a more detailed explanation for why I think the current isZIP64 check is incorrect.

This is from section 4.4.3 of the ZIP specification:
> 4.4.3 version needed to extract (2 bytes)
> 4.4.3.1 The minimum supported ZIP specification version needed 
> to extract the file, __mapped as above__. 

The key I think, is in the __mapped as above__. It seems to refer to section _4.4.2 version made by_ which describes how the version is encoded with the upper byte referring to the os, and the lower byte to the zip specification version.

ZIPFoundation seems to correctly handle both bytes of `versionMadeBy`, but incorrectly assumes both bytes of `versionNeededToExtract` refer to the ZIP version.

Of course the specification is a little vague, but I compared with how Info-Zip interprets it.

For example, I have a ZIP file whose entries' `versionNeededToExtract` equals 0000001100001010. ZIPFoundation interprets this as 778, which is higher than 45 so the isZIP64 check fails.
However, if I run `zipinfo -v` on the same file, it reports:
```
file system or operating system of origin:      Unix
version of encoding software:                   6.3
minimum file system compatibility required:     Unix
minimum software version required to extract:   1.0
```

This corresponds with the 2 separate byte interpretation of the `versionNeededToExtract` where 00000011 (3) refers to Unix, as specified in 4.4.2 and 00001010 (10) refers to version 1.0

It seems a lot of archives don't set the upper byte at all and leave it at 0, which is why the isZIP64 check mostly works. But I've already seen a bunch of ZIP files in the wild that can't be opened with ZIPFoundation because of this reason, even though they are not actually ZIP64.

I can email an example ZIP that suffers from this if you'd like.

I hope my explanation is clear enough. Keep up the good work!

**Comment by OCJvanDijk** [comment]
I guess you could still argue that the upper/lower byte interpretation doesn't really make sense, but it seems pervasive enough to support compatibility with it. The specification version itself will likely never get high enough to reach into the second byte anyway, and even if it did, then section 4.4.2 would be in trouble.

**Comment by weichsel** [comment]
Hi, 
Thanks for re-investigating this and sorry for the delayed reply. (I am only working on this project in small bursts from time to time 😶). 
With your detailed break-down and pointing out that `versionNeededToExtract` might pack the version info in the same way as `versionMadeBy` I now think that I closed the PR prematurely. Will re-open that.  
Do you know which library/program creates a version field filled with both bytes?  
Maybe we should add a test case that uses such an archive to your original PR.

**Comment by OCJvanDijk** [comment]
No idea which software creates these files, unfortunately, as I just encounter them from various sources on the web.
