### ISSUE TITLE
Removing entries from archives with access mode `read`

### ISSUE THREAD

**Issue by objecthub** [weichsel/ZIPFoundation#198]
# Summary

It is possible to remove entries from zip archives that are using access mode `read`.

# Steps to Reproduce

`archive.remove(entry)` succeeds for archives that have been created with access mode `read`. A new archive is written without `entry`.

# Expected Results

archive.remove(entry) should always fail if archive has been created with access mode `read`. The zip archive should not be touched in this case.

# Actual Results

A new archive without `entry` is being created via `archive.remove(entry)` replacing the former archive. This should not happen if `archive` is using access mode `read`.

# Related Note

I believe all that's needed is to add this line to the beginning of the `remove` method of class `Archive`:

```
guard self.accessMode != .read else { throw ArchiveError.unwritableArchive }
```

**Comment by weichsel** [comment]
Goody catch - Thanks for reporting this. 
Will be fixed in the next release!
