### ISSUE TITLE
Add support for NSProgress

### ISSUE THREAD

**Issue by steipete** [weichsel/ZIPFoundation#2]
`NSProgress` is somewhat a weird API, but it's the standard now on iOS/macOS and after a few release it now works really well. Would be great if zip/unzip operations would create a progress object so it's easy to populate a spinner with actual data instead of an indeterminate "working" state.

https://oleb.net/blog/2014/03/nsprogress/
http://jaanus.com/an-example-on-how-to-use-nsprogress/

**Comment by weichsel** [comment]
Yes, that would be a nice addition. Will try to get that into one of the upcoming releases.
