### ISSUE TITLE
Infinite loop when extract is called with bufferSize <= 0

### ISSUE THREAD

**Issue by valeriyvan** [weichsel/ZIPFoundation#204]
# Summary

When extract method is called with parameter bufferSize <= 0, function never returns.

# Steps to Reproduce

Call extract with bufferSize parameter 0.

# Expected Results

Method should throw or precondition should fire.

# Actual Results

Function never returns

# Regression & Version

# Related Link

**Comment by weichsel** [comment]
Hi Valeriy,
Good catch regarding zero buffer sizes. Looping indefinitely is definitely wrong here and we should handle this more gracefully. I saw that you added `preconditions` to catch this issue, but I wonder if a softer approach - like throwing an exception - would be better here.

**Comment by valeriyvan** [comment]
This is right case for precondition. But exception is also ok. Would you like me to add case to `ArchiveError`?

**Comment by weichsel** [comment]
@valeriyvan 
> Would you like me to add case to ArchiveError, e.g. invalidParameter?

Yes, please . I think a case like `invalidBufferSize` would be good.

**Comment by valeriyvan** [comment]
done
