### ISSUE TITLE
Integrity of `Data` read with `data` property

### ISSUE THREAD

**Issue by valeriyvan** [weichsel/ZIPFoundation#211]
Is it guaranteed that `Data` read with [`data`](https://github.com/weichsel/ZIPFoundation/blob/5276aa0eef90f04430b4f4a5814a78a0634564e5/Sources/ZIPFoundation/Archive%2BMemoryFile.swift#L17) property after any successful read or write operation represent valid zip archive which could be written to a file and later read with `Archive`? Shouldn't underlying memory file firstly be closed somehow?

**Comment by weichsel** [comment]
> Is it guaranteed that Data read with data property after any successful read or write operation represent valid zip archive which could be written to a file and later read with Archive?

Successful read operation: Reads should not have any side-effects on the archive content.
Successful write operation: We perform a `fflush` after each entry addition. So after `addEntry` has returned, `.data` of an in-memory archive should be valid. 

In-memory archives are initialized with [`funopen`](https://www.freebsd.org/cgi/man.cgi?query=funopen&sektion=3&manpath=freebsd-release-ports) and thereafter treated the same way as file-backed archives. So `fflush` should have the same effect.

Are you experiencing problems with in-memory archives?

**Comment by valeriyvan** [comment]
> Are you experiencing problems with in-memory archives?

No. Not yet. I ask because doc comment `Returns a 'Data' object containing a representation of the receiver.` gives no promises and no guarantees.

**Comment by weichsel** [comment]
👍 Let me know if you notice any integrity problems. 
I haven't used this part of the framework much myself so far. But from testing and reviewing the code, everything looked correct.
