### ISSUE TITLE
Usage of Consumer closure

### ISSUE THREAD

**Issue by vinczebalazs** [weichsel/ZIPFoundation#219]
Hi,

I would like to read an archive without writing it to the filesystem. I am a bit puzzled on how to use the `Consumer` closure. Because the closure is asynchronous and only chunks of data are passed in at a time, how would I know when was the last chunk read (i.e. when can I deserialize my full data)?

Thanks

**Comment by weichsel** [comment]
Hi,

> I am a bit puzzled on how to use the Consumer closure. Because the closure is asynchronous and only chunks of data are passed in at a time, how would I know when was the last chunk read (i.e. when can I deserialize my full data)?

There's a section about the Provider/Consumer closures in the README. The consumer closure is called until the end of the entry is reached. The size of the passed in `data` depends on the `bufferSize` (you can pass a custom value in for that or use the default):  
https://github.com/weichsel/ZIPFoundation#closure-based-reading-and-writing
