### ISSUE TITLE
Some files are missing after extracting ZIP

### ISSUE THREAD

**Issue by shlima** [weichsel/ZIPFoundation#224]
# Summary

Some files are missing after extracting ZIP archive on iOS. I tried to create an archive without compression or from different OS versions but it did not help. Everything works fine when the archive is slightly smaller.

# Steps to Reproduce

Download the [archive](https://around-wiki-aws-01.storage.yandexcloud.net/export/remote/01/0b/81/2f2530b9-c214-4ef1-bd7d-08763982829c/RU_ru.zip) (~3GiB) and try to extract it on your iOS and laptop, a lot of files will be missing on iOS

# Expected Results

Around `192 309` files after unpacking on a computer

# Actual Results

Around `34 309` files after unpacking on IOS

# Regression & Version

`ZIPFoundation (0.9.12)`

**Comment by weichsel** [comment]
Can you share the code you are using to extract?  
Thanks for providing a file to reproduce the issue, but its size makes it a bit unhandy. Is there anything in common between the entries that are missing (e.g. are they particularly big or are they symlinks, ...).

**Comment by shlima** [comment]
Actually the size of each file is 5 kb-10mb. These are regular files on disk not symbolic links. Files are organized into nested folder structures like:

```
photos/a/b/c/1.jpeg
photos/a/b/d/2.jpeg
photos/a/b/e/3.jpeg
photos/b/a/b/4.jpeg
```

We use flutter plugin [flutter_archive](https://github.com/kineapps/flutter_archive) which uses a **ZIPFoundation** under the hood and **native** swift code with **ZIPFoundation**. Both applications give the same result: many files are lost after extraction.

I am not an iOS developer, but it seems that I have provided the necessary piece of code here:

```swift
try FileManager.default.createDirectory(atPath: archiveDirectory.path, withIntermediateDirectories: true, attributes: nil)
let progress = Progress()
try FileManager.default.unzipItem(at: archiveURL, to: archiveDirectory, skipCRC32: true, progress: progress)
```

**Comment by shlima** [comment]
I will say it again, If we make ZIP archives up to `1GiB` in size, everything works like clockwork.

**Comment by weichsel** [comment]
> So the reason might be in ZIP64?

Yes, this would explain it.

**Comment by weichsel** [comment]
Update:  
I just investigated this issue and the underlying problem is indeed missing ZIP 64 support.  
The `totalNumberOfEntriesOnDisk` in the `EndOfCentralDirectoryRecord` exceeds the non-ZIP64 limit defined by `UInt16.max`. Archives with >`UInt16.max` entries require ZIP64, which we currently don't support.
