### ISSUE TITLE
cannot link ZIPFoundation 0.9.x in debug with xcode 12.5

### ISSUE THREAD

**Issue by alienpenguin** [weichsel/ZIPFoundation#225]
# Summary
My app using ZIPFoundation cannot link anymore in debug with xcode 12.5 due to the following error:
Undefined symbols for architecture arm64:
  "Swift._ArrayBuffer._copyContents(initializing: Swift.UnsafeMutableBufferPointer<A>) -> (Swift.IndexingIterator<Swift._ArrayBuffer<A>>, Swift.Int)", referenced from:
      generic specialization <serialized, Swift._ArrayBuffer<Swift.Int8>> of Swift._copyCollectionToContiguousArray<A where A: Swift.Collection>(A) -> Swift.ContiguousArray<A.Element> in AppDelegate.o

# Steps to Reproduce
i was happily using ZIPFoundation 0.9.9 within my project with xcode12.4. After upgrading to xcode 12.5 i had to recompile ZIPFoundation due to swift compiler changes. After that i recompiled ZIPFoundation i tried to compile my project but could not due to the error above.
A few notes:
1) i tried upgrading to ZF 0.9.12 or even latest git: same error
2) compiling in release works as expected
3) removing ZF from my project i managed to compile it in debug, so the problem resides within the linking in debug with ZF

# Expected Results
successful linking

# Actual Results
linking error: Undefined symbols for architecture arm64:
  "Swift._ArrayBuffer._copyContents(initializing: Swift.UnsafeMutableBufferPointer<A>) -> (Swift.IndexingIterator<Swift._ArrayBuffer<A>>, Swift.Int)", referenced from:
      generic specialization <serialized, Swift._ArrayBuffer<Swift.Int8>> of Swift._copyCollectionToContiguousArray<A where A: Swift.Collection>(A) -> Swift.ContiguousArray<A.Element> in AppDelegate.o

# Regression & Version
xcode 12.5 and ZF 0.9.9 / 0.9.12 / git 2021-05-12

# Related Link

**Comment by weichsel** [comment]
What are you using to integrate ZIP Foundation into your project?
Swift Package Manager, CocoaPods, Carthage? Or did you manually add the .xcodeproj to your project?

**Comment by alienpenguin** [comment]
i was usually compiling it manually and then adding the resulting framework into my git repo, i tried switching to swift package manager and the result was identical

**Comment by weichsel** [comment]
Just tested building and linking with a small sample project using Xcode 12.5. Integration via SPM. Tried iOS device and Simulator builds. All works as expected. 🤷‍♂️
How did you build the .framework when you manually built it? If it was a built for the Simulator with the "Debug" configuration, it might miss an ARM64 slice - which would explain the error message. Maybe the old framework is still lying around and picked up by Xcode?

**Comment by juanpaternina** [comment]
HI, Wechsel. I'm using a library that is using this library as dependency and I facing same issue.

This is happening after upgrade my Xcode to 12.5, if there is any other information that you need 
I will happy to help you.

<img width="1440" alt="118514077-de712100-b6f9-11eb-85c5-260d651e9f80" src="https://user-images.githubusercontent.com/21976360/118656108-d2479b00-b7af-11eb-8727-c4e319e14ce7.png">

**Comment by weichsel** [comment]
@juanpaternina What are you using to manage the dependencies? 
Before trying anything else, I'd try to close Xcode and wipe "Derived Data".
If this doesn't fix it, you can try to link "Compression.framework" in the target that consumes ZIP Foundation.

**Comment by juanpaternina** [comment]
Thanks for your answer @weichsel  
I will try to make it and let you know if it's works.

**Comment by alienpenguin** [comment]
@weichsel sorry for the late reply; to avoid mistakes i completely removed the ZIPFoundation compiled manually from my project and i am relying only on the swift package one. 
I tried searching through the xcodeproj file and the only mentioning of ZIPFoundation is in the linking framework part along firebase and phonenumberkit.
the behaviour is consistent: builds flawlessly in "release" if i build with the archive command while it throws the linking error i posted when i build it in debug. Do you have any suggestion?

**Comment by weichsel** [comment]
> I tried searching through the xcodeproj file and the only mentioning of ZIPFoundation is in the linking framework part along firebase and phonenumberkit.

Is your project the consumer of ZIP Foundation or is it built as transitive dependency of one of your other dependencies?  

I am also not sure if ZIP Foundation is the culprit here because the symbols (`(Swift.IndexingIterator<Swift._ArrayBuffer>, Swift.Int)`) in your original post are basic Swift types and not related to ZIP Foundation.  
Have you tried deleting Derived Data and maybe also resetting the SPM Cache in Xcode ("File" -> "Swift Packages" -> "Reset Package Caches")?

**Comment by alienpenguin** [comment]
@weichsel if i comment out the inclusion of ZIPFoundation (and just that) the app builds in debug mode without issues.
The app is using ZIPFoundation directly to: 
- unzip a binary package containing additional grpahics
- zip log files that are attached to email for report

i deleted $HOME/Library/Developer/Xcode/DerivedData/* but after rebuilding nothing changed

i tried just now to reset package caches as you suggested but the result is always the same

i found other people lamenting similar issue (specially react native apps) with the new xcode [here](https://stackoverflow.com/questions/67311980/swift-arraybuffer-copycontents-on-xcode), [here](https://github.com/meedan/react-native-share-menu/issues/123) and [here](https://stackoverflow.com/questions/67367050/build-is-failing-for-older-projects-for-react-native-ios-xcode-version-12-5)

**Comment by weichsel** [comment]
It'd be interesting wether the errors come from the way your project is set up, or from your Xcode environment.
Do you have any custom Swift Toolchains installed?  
What happens when you create a fresh project and configure ZIP Foundation as package dependency via Xcode?

You could also try the steps described here: https://github.com/facebook/react-native/issues/31179#issuecomment-829536845

**Comment by alienpenguin** [comment]
i have no custom toolchain installed
i have looked for the settings mentioned in that issue and i have no such path in my project, i tried also changing the "Alway embed swift libraries" in the debug setting but unfortunately it had no effect.

Do you have any sample project that you want me to try?

**Comment by weichsel** [comment]
This is a very simple test app that consumes the ZIP Foundation package and reads an included archive:
[ZIPTest.zip](https://github.com/weichsel/ZIPFoundation/files/6526546/ZIPTest.zip)

You could try if this barebones setup works on your machine.

**Comment by alienpenguin** [comment]
@weichesel, i compiled it successfully, so it must be an xcode project setting that triggers this error when linking ZIPFoundation

**Comment by weichsel** [comment]
@alienpenguin Maybe you can use the sample project (which uses the Xcode defaults) to compare the build settings to your project. At first I'd have a look at the `ARCHS` and `SWIFT_VERSION` settings of all your projects/targets.

**Comment by zrg-team** [comment]
is everyone resolved it?

**Comment by juanpaternina** [comment]
I already solved, if your error Is with react-native, I can tell you how i solved it. Thanks to @weichsel, nice work.

**Comment by alienpenguin** [comment]
@weichsel thanks for your support at the end of the day i rebooted the macbook and the issue went away...
