### ISSUE TITLE
Copy some entries from an archive to another archive

### ISSUE THREAD

**Issue by luhahaha** [weichsel/ZIPFoundation#226]
I would like to copy some entries from a file to another file, which is the best way to do it?

**Comment by weichsel** [comment]
You can instantiate two instances of `Archive`. One with `accessMode: .read` and the other with `.update`.  
Then you can iterate over the "read" archive (`for entry in readArchive`) and add entries to the "update" archive (`updateArchive.addEntry(...)`). 

To avoid filesystem roundtrips, I'd use the [closure-based API ](https://github.com/weichsel/ZIPFoundation#closure-based-reading-and-writing). You can pass the data that you read via `archive.extract(entry, consumer: { ... }` to the closure based variant of `.addEntry`.
