### ISSUE TITLE
Plans for next release

### ISSUE THREAD

**Issue by kernandreas** [weichsel/ZIPFoundation#235]
Hello @weichsel 

Thank you for building this great library. I was evaluating it for our project. We create zip files of large directories (thousands of files, hundred of megabytes). And it does a great job. Well since developer experience is also important I was happy to see #227 merged.

This leads me to the question: What are the plans for the next release which includes this PR? Do you need any help for it?

All the best,  
Andreas.

**Comment by weichsel** [comment]
Hi @kernandreas ,

I am currently trying to get #230 merged. The PR is in great shape, we are just trying to get some final refinements done.  
Can't really promise a release date but I hope to tag a new release within the next days/weeks.

**Comment by kernandreas** [comment]
Thank you for getting back. This sounds great. Looking forward for the release.
