### ISSUE TITLE
Fail to open zip archive

### ISSUE THREAD

**Issue by valeriyvan** [weichsel/ZIPFoundation#236]
# Summary

Fail to open particular zip archive which could be normally open with zip cli.

[AF8A6BBE-BFC4-4503-9970-6160E51449CB.zip](https://github.com/weichsel/ZIPFoundation/files/7648728/AF8A6BBE-BFC4-4503-9970-6160E51449CB.zip)

# Steps to Reproduce

Try open attached zip archive.

# Expected Results

Zip archive should be open.

# Actual Results

Fail to open.

# Regression & Version

0.9.13

# Related Link

**Comment by weichsel** [comment]
Can you share your code?

I just performed a brief experiment and was able to iterate over the provided archive with ZIPFoundation 0.9.13. Entry extraction also worked.
