### ISSUE TITLE
Is it possible to use ZIPFoundation to compress data into multiple zip files?

### ISSUE THREAD

**Issue by jonah-neugass-ck** [weichsel/ZIPFoundation#237]
Just wondering if it is possible to split data across multiple zip files using ZIPFoundation like it is using command line zip. Thanks!

**Comment by weichsel** [comment]
Files spanning multiple "disks" (= archives) are currently not supported. 
What's your use case?

**Comment by jonah-neugass-ck** [comment]
I'm working on a project that requires storage and  transmission of large sets of JSON data over the network with high reliability.

**Comment by weichsel** [comment]
If you have full control on both, the sender and receiver sides, you can skip the "ZIP" part and just chunk, compress, transfer, decompress and concatenate.  

ZIP ≠ compression. ZIP is an archiving format (= store e.g. a directory structure in a single file) with optional compression. 
ZIPFoundation does provide a Swift wrapper around libcompression though. Our `Data+Compression.swift` extension provides a closure-based API to (de)compress chunks of `Data` that could be helpful for your use case.

**Comment by jonah-neugass-ck** [comment]
Awesome, thanks!
