### ISSUE TITLE
Reading zipped contents from Data

### ISSUE THREAD

**Issue by MLDev042** [weichsel/ZIPFoundation#241]
My application zips contents of a directory, then writes the zipped content to disc. The zipped content is then converted to Data (using Data(contentsOf: url)), so that the content can be transported with an object using multipeer connectivity.

My question is how can I read the zipped contents after being converted to Data?

**Comment by weichsel** [comment]
> My question is how can I read the zipped contents after being converted to Data?

You mean on the receivers end?
Either you write it to a file and use the `FileManager` extension to extract, or you use an in-memory `Archive`.
We provide an [initializer](https://github.com/weichsel/ZIPFoundation/blob/development/Sources/ZIPFoundation/Archive.swift#L191) on `Archive` that takes a `data` parameter. This can be used to iterate-over/extract archives that do _not_ have a file system representation. It might also be possible to eliminate the file system roundtrip when creating the archive. Have a look at the [In-memory archive section](https://github.com/weichsel/ZIPFoundation#in-memory-archives) of the README.

**Comment by MLDev042** [comment]
I understand now. Thank you for the clarification!
