### ISSUE TITLE
Error while creating ZIP stream: The operation couldn’t be completed. (ZIPFoundation.Archive.ArchiveError error 0.)

### ISSUE THREAD

**Issue by Strife91** [weichsel/ZIPFoundation#247]
This happens when calling DFUFirmware(urlToZipFile: url) when using the iOSDFULibrary.

Firmware url: file:///var/mobile/Containers/Data/Application/6CF4B455-9787-4EFE-BEDC-D6A15DAA8524/Documents/firmwares/1-2.0.7.zip

Anyone know how to solve this problem?

**Comment by Strife91** [comment]
> Maybe the zip archive at that path isn't a valid archive?
> 
> Not sure in what context you are experiencing this error. Are you using https://github.com/NordicSemiconductor/IOS-DFU-Library? Maybe you can look there if this is a known issue?
> 
> I am closing this for now. Feel free to re-open if the issue is related to unzipping.

Yes. I'm using the IOS-DFU-Library.  The error doesn't always occur. It seems to work when I launch the app for the first time. 

I went to nordics issue page, but they recommended I come here. lol

**Comment by weichsel** [comment]
Can you verify that `/var/mobile/Containers/Data/Application/6CF4B455-9787-4EFE-BEDC-D6A15DAA8524/Documents/firmwares/1-2.0.7.zip` is a valid ZIP archive?

**Comment by weichsel** [comment]
Thanks for the update, great that you found the issue. 
Since this is unrelated to framework code, I'll leave the issue closed.
