### ISSUE TITLE
v0.9.14 not (yet) available through CocoaPods

### ISSUE THREAD

**Issue by thirtified** [weichsel/ZIPFoundation#251]
# Summary
CocoaPods doesn't list ZIPFoundation's latest version 0.9.14 but only 0.9.13.

# Steps to Reproduce
Check any of the following:
- https://github.com/CocoaPods/Specs/tree/master/Specs/1/6/1/ZIPFoundation
- https://cocoapods.org/pods/ZIPFoundation

Both above entries show 0.9.13 as the last available version.

# Expected Results
CocoaPods should list 0.9.14 as the most recent ZIPFoundation version.

# Actual Results
CocoaPods lists 0.9.13 as the most recent ZIPFoundation version.

**Comment by weichsel** [comment]
Fixed - thanks for making me aware of this. 
https://cocoapods.org/pods/ZIPFoundation

**Comment by thirtified** [comment]
Thank you! :relaxed:
