### ISSUE TITLE
Fails unzip on this archive

### ISSUE THREAD

**Issue by honzaskypala** [weichsel/ZIPFoundation#254]
Unziping fails in the middle of [this archive](https://drive.google.com/u/0/uc?id=1c-BOyl9GGLK3VMoGWshKCFLrbcuXhbQm&export=download). Some of the files are unzipped, but then the unzipping process stops and the rest is not unzipped.

Unzipping the same file on my Mac and PC using built-in unzip in Finder or Explorer is working fine, no issues. All files are unzipped there.

(Yes, it is using a different suffix, but it is a ZIP archive; and it is working correctly on other files with the same suffix)

Simple code for unzipping, nothing extra...

```
import SwiftUI
import UniformTypeIdentifiers
import ZIPFoundation

struct Unzip621: View {
    @State private var selectFile = false
    
    var body: some View {
        Button("Unzip file") {
            selectFile.toggle()
        }
        .fileImporter(isPresented: $selectFile, allowedContentTypes: [UTType.init(filenameExtension: "vmod")!]) { (res) in
            do {
                guard let archiveUrl = try? res.get(),
                      archiveUrl.startAccessingSecurityScopedResource()
                else { return }
                var destinationUrl = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
                destinationUrl.appendPathComponent("Test", conformingTo: .folder)
                let fileManager = FileManager.default
                try fileManager.createDirectory(at: destinationUrl, withIntermediateDirectories: true, attributes: nil)
                try fileManager.unzipItem(at: archiveUrl, to: destinationUrl)
            } catch {
                print("Error")
            }
        }
    }
}
```

**Comment by weichsel** [comment]
Hi,

The archive you linked to, contains files with duplicate names (only differing in case sensitivity):
The first occurrence of such a file-pair I found was:
```
- images/BOARD17 - Shade-Cursed Lair.jpg   OK
- images/BOARD17 - Shade-cursed Lair.jpg   OK
```

If you are extracting to an case-insensitive file system like the default APFS on the Mac, ZIP Foundation can't create the second entry because the file already exists.
