### ISSUE TITLE
I am not able to zip the file from source url

### ISSUE THREAD

**Issue by Zulqurn** [weichsel/ZIPFoundation#260]
As I am trying to zip the file from url `_url : file:///private/var/mobile/Library/Mobile%20Documents/com~apple~CloudDocs/Downloads/delete_icon.pdf` i am getting this error The file “delete_icon.pdf” couldn’t be opened because there is no such file. Your help will be very well appreciated. Thanks in advance.

**Comment by weichsel** [comment]
Does the file exist? Do you have permissions to read from the Downloads folder?

**Comment by Zulqurn** [comment]
Thanks @weichsel I got the issue actually the privacy domain setting was missing as the problem was related to startAccessingSecurityScopedResource and stopAccessingSecurityScopedResource scope.
Best Regards

**Comment by weichsel** [comment]
Glad you could figure it out 👍
