### ISSUE TITLE
UNZIP to new directory not working?

### ISSUE THREAD

**Issue by haiderashfaq** [weichsel/ZIPFoundation#28]
```
let directoryURL: URL = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
let folderPath: URL = directoryURL.appendingPathComponent("/AR/DataNFT", isDirectory: true)

let fileManager = FileManager.default

if !fileManager.fileExists(atPath: folderPath.path) {
    do {
        
              try fileManager.createDirectory(at: folderPath, withIntermediateDirectories: true, attributes: nil)
    } catch {
        print("Couldn't create document directory")
    }
}

try fileManager.unzipItem(at: response.destinationURL!, to: folderPath)
```

I am getting my downloaded files unzipped some of them into "AR/DataNFT" as expected but some of them are getting into another folder which has the download name for example "AR/DataNFT/DownloadName/(unzipped files)"

Why is this behaviour of unzip function temperamental? Am i doing something wrong?

**Comment by weichsel** [comment]
Can you share a ZIP file that exposes this problem.  
The defined behaviour is, that the folder structure within a ZIP file is recreated at `folderPath`.
Some archives may have an additional folder at their root level, this folder will be also be recreated. Other archives don't contain a common root folder and have files and folders mixed at their root level.
