### ISSUE TITLE
v0.9.17 not (yet) available through CocoaPods

### ISSUE THREAD

**Issue by Jonas1893** [weichsel/ZIPFoundation#300]
# Summary
Same problem as in #251, so just copied contents of the ticket with updated versions :)

CocoaPods doesn't list ZIPFoundation's latest version 0.9.17 but only 0.9.16.

# Steps to Reproduce
Check any of the following:
- https://github.com/CocoaPods/Specs/tree/master/Specs/1/6/1/ZIPFoundation
- https://cocoapods.org/pods/ZIPFoundation
Both above entries show 0.9.16 as the last available version.

# Expected Results
CocoaPods should list 0.9.17 as the most recent ZIPFoundation version.

# Actual Results
CocoaPods lists 0.9.16 as the most recent ZIPFoundation version.

# Related Link
See also https://github.com/weichsel/ZIPFoundation/issues/251#issue-1370133519

**Comment by weichsel** [comment]
I currently can't push the podspec because visionOS (which is supported now in ZIP Foundation) currently doesn't validate in CocoaPods: https://github.com/CocoaPods/CocoaPods/issues/12118

**Comment by jainricha** [comment]
Any timeline by when the latest version will be available in Cocoapod?

**Comment by jainricha** [comment]
@weichsel Isn't visionOS support is resolved with this PR: [Support visionos in pod lib lint](https://github.com/CocoaPods/CocoaPods/pull/12159) ?

**Comment by weichsel** [comment]
> @weichsel Isn't visionOS support is resolved with this PR: https://github.com/CocoaPods/CocoaPods/pull/12159 ?

Yes, but there's no new CocoaPods release yet.

**Comment by jdanthinne** [comment]
Waiting for 0.9.18 to be published as well… Is there something to do?

**Comment by cristibaluta** [comment]
I guess we are all waiting for the privacy manifest to reach cocoapods? Can we have a 0.9.16.1 in this case?

**Comment by sumitmorey** [comment]
My app release is in a weeks time. 
Waiting for 0.9.18 as it has fix for path traversal vulnerability.

**Comment by philips77** [comment]
> Yes, but there's no new CocoaPods release yet.

CocoaPods 1.15.x with `visionOS` support was released some time ago. Could you, please, release 0.9.18 no Pods?

**Comment by sumitmorey** [comment]
0.9.18 can be included as below. Veracode tool won't scan it as their vulnerablity database is not updated.

 pod 'ZIPFoundation', :git => 'https://github.com/weichsel/ZIPFoundation.git', :tag => '0.9.18'

**Comment by weichsel** [comment]
Pod validation now did run through with the latest version. 
0.9.18 is now also available when using CocoaPods.
