### ISSUE TITLE
Bump minimum version for Swift 5.9 to stop deprecation warnings

### ISSUE THREAD

**Issue by brzzdev** [weichsel/ZIPFoundation#302]
# Summary
When building ZipFoundation (particularly noticeable in command line) warnings are given stating actual supported versions

![Screenshot 2023-11-24 at 18 11 02](https://github.com/weichsel/ZIPFoundation/assets/15687450/d3b0b9f6-67dc-4811-851b-454567e5af5a)

**Comment by brzzdev** [comment]
Looks like this is already fixed but pending release?

**Comment by weichsel** [comment]
> Looks like this is already fixed but pending release?

Yes, will be part of the next release.
