### ISSUE TITLE
Vulnerability : An issue in ZIPFoundation v0.9.16 allows attackers to execute a path traversal via extracting a crafted zip file

### ISSUE THREAD

**Issue by jainricha** [weichsel/ZIPFoundation#303]
# Summary
Blackduck scan reports the below security issue:
An issue in ZIPFoundation v0.9.16 allows attackers to execute a path traversal via extracting a crafted zip file.

Is there any expected timeline by when this can be expected to fix? or If there is already a fix available for this.

Please suggest.

**Comment by weichsel** [comment]
Closing because this is a duplicate of https://github.com/weichsel/ZIPFoundation/issues/281 and https://github.com/weichsel/ZIPFoundation/issues/282.
