### ISSUE TITLE
Extracting JSON file from archive returns jumbled data

### ISSUE THREAD

**Issue by Lancelotbronner** [weichsel/ZIPFoundation#305]
# Summary

I zipped via finder a JSON database (selected a bunch of folders and `right-click > Compress`).
I then extract those when needed, most of the files are just fine but some of them come back as garbage.

Some files are also just missing seemingly random pieces of text.

# Steps to Reproduce

1. Archive 2 directories containing JSON files using Finder (via selecting both directories, `right-click > Compress`)
2. Extract the file from the archive using the following snippet:

```swift
let archive = Archive(url: url, accessMode: .read)
let entry = archive["example.json"]
var data: Data!
_ = try database.extract(entry, skipCRC32: true) {
    data = $0
}

print(String(data: data, encoding: .utf8))
```

3. This prints `nil` as it fails to recognize UTF-8

# Expected Results

```json
{
    "count": 13,
    "next": null,
    "previous": null,
    "results": [
        {
            "name": "ja-Hrkt",
            "url": "/api/v2/language/1/"
        },
        {
            "name": "roomaji",
            "url": "/api/v2/language/2/"
        },
        {
            "name": "ko",
            "url": "/api/v2/language/3/"
        },
        {
            "name": "zh-Hant",
            "url": "/api/v2/language/4/"
        },
        {
            "name": "fr",
            "url": "/api/v2/language/5/"
        },
        {
            "name": "de",
            "url": "/api/v2/language/6/"
        },
        {
            "name": "es",
            "url": "/api/v2/language/7/"
        },
        {
            "name": "it",
            "url": "/api/v2/language/8/"
        },
        {
            "name": "en",
            "url": "/api/v2/language/9/"
        },
        {
            "name": "cs",
            "url": "/api/v2/language/10/"
        },
        {
            "name": "ja",
            "url": "/api/v2/language/11/"
        },
        {
            "name": "zh-Hans",
            "url": "/api/v2/language/12/"
        },
        {
            "name": "pt-BR",
            "url": "/api/v2/language/13/"
        }
    ]
}
```

# Actual Results

```
ï0Nﬂ‰Ä]Áõú‚P†îÃ†∏¿˛õ‚Sﬂ‰Ä]ÁõüîàÇ§∏–%ú‚‡0ú‚`Y§∏üî`Y§∏@B“‰Ä]Áõ–Ñ:‰`Y§∏®2ú‚`Y§∏»3ú‚`Y§∏P&ú‚»ß¢∏x0ú‚–÷”‰‰∏°∏®6ú‚(ÿ”‰‰∏°∏»?ú‚÷”‰‰∏°∏®Bú‚®◊”‰‰∏°∏ÿBú‚XÆŸ‰4nÁõ–
ú‚êÿ”‰‰∏°∏@oú‚pÿ”‰‰∏°∏poú‚Pÿ”‰‰∏°∏†oú‚Äpú‚‰∏°∏vú‚Hqú‚‰∏°∏Pvú‚rú‚‰∏°∏òvú‚ µº‚Ä]Áõ∞1ú‚Ä]ÁõP|ú‚hNÁõò~ú‚¿%ú‚Ä]ÁõHÄú‚àãú‚‰∏°∏`èú‚Ä¥º‚Ä]ÁõÿÄú‚Ä]Áõ iﬂ‰Ä]Áõ∏¡ú‚ÿ|ﬂ‰Ä]Áõ0Nœ‰Ä]Áõ@Àú‚:‰ÿ<ÁõpÀú‚@`ú‚Ä]ÁõŒú‚hNÁõ¿Œú‚®˙º‚Ä]Áõ*Ω‚Ä]Áõ∞±€‰Ä]Áõp“ú‚‘ú‚Ä]Áõà‘ú‚Ä]Áõ»®ﬂ‰Ä]ÁõH©ﬂ‰Ä]ÁõX’ú‚Ä]Áõ¿’ú‚Ä]Áõ(÷ú‚Ä]Áõ∏5ú‚Ä]Áõ(¬ﬂ‰Ä]Áõx6Ω‚Ä]Áõ‡0ú‚Ä]Áõp÷ú‚h3ú‚Ä]Áõ»3ú‚Ä]Áõ»B’‰Ä]Áõ
```

# Regression & Version

ZipFoundation v0.9.17
macOS Sonoma 14.3 Beta (23D5033f)
Xcode 15.1 targeting macOS

# Related Link

**Comment by Lancelotbronner** [comment]
I'm aware I'm supposed to handle the case where more than one chunks are sent. Currently I'm trying with small files which fit into a single chunk.

I would also expect to receive valid UTF-8 (if not for maybe the last few bytes) even if chunks are missing, so I'm guessing something happened to those entries.

**Comment by Lancelotbronner** [comment]
I've tried with archives using a single top-level directory and that didn't change anything.

I've also noticed that every run seems to corrupt different files, so that makes me inclined to think the issue lies in the reading or decompressing.

**Comment by weichsel** [comment]
> let archive = Archive(url: url, accessMode: .read)
let entry = archive["example.json"]
var data: Data!
_ = try database.extract(entry, skipCRC32: true) {

In this snippet you are retrieving an entry from `archive`, but then calling `extract` on a different `Archive` instance called `database`. This doesn't seem right.

**Comment by Lancelotbronner** [comment]
Ah, I was renaming things on Github for the example because the names were specific to my project.

I am using the same archive, also tried in a small project separately and got the same result.

**Comment by weichsel** [comment]
Why are you setting `skipCRC32: true`? What happens when you drop that parameter (which equals `skipCRC32: false`)? Are the checksums correct?

**Comment by Lancelotbronner** [comment]
Yes they are, the archive isn't downloaded from the internet it's local.

I also tested with zipping tools and they don't seem to have any issues.

I've also tried with Apple's compression library and it doesn't have any issues, though it doesn't allow extracting files individually.

**Comment by weichsel** [comment]
Can you share your code and the archive?
