### ISSUE TITLE
0.9.18

### ISSUE THREAD

**Issue by MarcoEidinger** [weichsel/ZIPFoundation#307]
**Is your feature request related to a problem? Please describe.**
Merged fixes for
- https://github.com/weichsel/ZIPFoundation/issues/306
- https://github.com/weichsel/ZIPFoundation/issues/304
are not easily accessible for SPM consumption

**Describe the solution you'd like**
Publishing a new GitHub release that contains the changes for the two fixed issues mentioned above

**Describe alternatives you've considered**
Using branch or commit as dependency rule to resolve package version

**Comment by takeshi-p0601** [comment]
Hi, thank you for the wonderful library
I also hope this issue gets resolved.
