### ISSUE TITLE
I have a question for Privacy Manifest.

### ISSUE THREAD

**Issue by wlxo0401** [weichsel/ZIPFoundation#309]
I discovered a new while testing. 

Until now, most of the libraries that have added PrivacyInfo have not been marked in PrivacyReport. 

However, when an item is added to the 'Privacy Nutrition Label Types', the library name is displayed in the PrivacyReport. 

Many libraries have updated PrivacyInfo without adding anything from 'Privacy Nutrition Label Types'.

Does anyone know about this? Is 'Privacy Nutrition Label Types' a must-have item? 

Or is it not necessary to display it in the privacy report?

ZIPFoundation is the only library I tested that appears in PrivacyReport. 

Is there a reason why you added an item??

Please feel free to leave opinion.

The 'PrivacyReport' I'm talking about can be downloaded as a PDF if you archive the app.

https://developer.apple.com/videos/play/wwdc2023/10060/
Please refer to 3:20.

1. Open your project in Xcode.

2. Choose Product > Archive. Xcode creates the archive and reveals it in the organizer.

3. Control-click the archive in the organizer and choose Generate Privacy Report.

(I used a translator.)

**Comment by weichsel** [comment]
> Does anyone know about this? Is 'Privacy Nutrition Label Types' a must-have item?

IIRC, the item was required. But since none of the label types is applicable to ZIP Foundation, we just provide an empty list.
