### ISSUE TITLE
Deprecated Init Syntax Still Present in Readme file

### ISSUE THREAD

**Issue by hbowie** [weichsel/ZIPFoundation#317]
I have an app called Notenik that makes use of ZIPFoundation. I've noticed lately that I get a build issue for my app saying that my usage of 'init(url:accessMode:preferredEncoding:)' is deprecated, and advising me to use the throwing initializer instead. Yet the section of the GitHub readme file talking about Creating Archives seems to still use the same syntax that I'm using, so I'm not entirely sure what I'm supposed to be doing differently.

**Comment by Partwood** [comment]
Was just going to post this issue myself, just added zip foundation to a swift project via swiftpm, used the example and immediately got the deprecation notice. Makes it hard to get started.

**Comment by skythomp16** [comment]
Came here to post the same thing.  Does anyone have an updated sample of compressing files into zip format??

**Comment by seabjackson** [comment]
Yep, this is still happening and a tad confusing
