### ISSUE TITLE
Some functions are only available on OS X 10.11 or newer

### ISSUE THREAD

**Issue by YugoCode** [weichsel/ZIPFoundation#32]
I get these three errors while compiling:

> 'compression_stream_init' is only available on OS X 10.11 or newer
> 'compression_stream_process' is only available on OS X 10.11 or newer
> 'compression_stream_destroy' is only available on OS X 10.11 or newer

Could fix it with: 

```
if #available(OSX 10.11, *) {
	// Use of one the functions above
} 
else {
	// Fallback on earlier versions
}
```

**Comment by weichsel** [comment]
This is a known issue. You'll have to raise the deployment target of your project to at least macOS 10.11.
The Swift Package Manager currently does not offer any flag to set a minimum deployment target for a package. More details can be found here: https://github.com/weichsel/ZIPFoundation/issues/30
