### ISSUE TITLE
xcode invalidCompressionMethod error (compression method=lzma)

### ISSUE THREAD

**Issue by codethesolution** [weichsel/ZIPFoundation#321]
I am having issues extracting certain zip archives in my app. I am building a MacOS application (miminum target: 13.1) using xCode version 15.4 (15F31d). I am using the most recent version of ZipFoundation. I have performed an update to ensure latest version is being used: Installing ZIPFoundation 0.9.19 (was 0.9.16).  When I explore the archive's properties using 'file', I see: "Zip archive data, at least v6.3 to extract, compression method=lzma".

**Comment by weichsel** [comment]
Hi, 
ZIP Foundation does not support `LZMA` compression.
Currently, uncompressed and `deflate` (the "default" compression format for ZIP archives) compressed archives are supported.
