### ISSUE TITLE
Swift 6 compilation error

### ISSUE THREAD

**Issue by viktasidenfy** [weichsel/ZIPFoundation#327]
# Summary

The following code does not compile with the Swift 6 language:

<img width="1024" alt="Screenshot 2024-07-16 at 12 14 52" src="https://github.com/user-attachments/assets/916acd92-aa90-4ac2-90e7-0348265eff3e">

**Comment by fpseverino** [comment]
There is [a branch](https://github.com/weichsel/ZIPFoundation/tree/chore/swift6) that should fix it, but it still throws errors when I run it: https://github.com/vapor-community/PassKit/actions/runs/10263910571/job/28396769308?pr=10#step:5:2572

**Comment by fpseverino** [comment]
Disabling TSAN it points more clearly to an error https://github.com/vapor-community/PassKit/actions/runs/10319401289/job/28567702710?pr=10#step:5:2683

[This is the line](https://github.com/weichsel/ZIPFoundation/blob/chore/swift6/Sources/ZIPFoundation/Data%2BSerialization.swift#L34) that causes the error

**Comment by maclee99** [comment]
FYI

https://stackoverflow.com/questions/42252124/fatal-error-load-from-misaligned-raw-pointer

**Comment by microtherion** [comment]
@maclee99 this is unnecessarily complex, you can just do an unaligned load: https://github.com/weichsel/ZIPFoundation/pull/339
