### ISSUE TITLE
Building with Xcode 16 B5 to a device running iOS 18.1 (22B5007p) crashes on app start

### ISSUE THREAD

**Issue by JagCesar** [weichsel/ZIPFoundation#330]
# Summary
Can't run an app built with Xcode 16 B5 on a device running iOS 18.1 (22b5007p).

# Steps to Reproduce
Add latest tag of ZIPFoundation as Swift Package dependency. Build to device.

# Expected Results
App should start normally

# Actual Results
Crash on app start with the following error in the console

```
dyld[94780]: Library not loaded: /usr/lib/swift/libswift_errno.dylib
  Referenced from: <22742062-D067-3857-BE55-7E34DBF0BFC9> /private/var/containers/Bundle/Application/9354DF9B-398F-4ED5-B7F4-DD8B72B169A2/Ambre.app/Ambre.debug.dylib
  Reason: tried: '/usr/lib/system/introspection/libswift_errno.dylib' (no such file, not in dyld cache), '/usr/lib/swift/libswift_errno.dylib' (no such file), '/private/preboot/Cryptexes/OS/usr/lib/swift/libswift_errno.dylib' (no such file), '/usr/lib/swift/libswift_errno.dylib' (no such file, not in dyld cache)
Message from debugger: killed
```

# Regression & Version

# Related Link

**Comment by weichsel** [comment]
Hi Cesar,
I am unable to reproduce this. Please re-open if you still encounter this issue.

**Comment by jhoughjr** [comment]
must be an Xcode thing happens to me for my app
