### ISSUE TITLE
Cannot extract archive of directory

### ISSUE THREAD

**Issue by IgorMuzyka** [weichsel/ZIPFoundation#336]
# Summary
A simple zip of directory crashes when for some reason trying to rename temporary file to `sourceURL`???

# Steps to Reproduce
Unzip a directory in a freshly created empty directory.
```swift
let fileManager: FileManager = .default
try fileManager.createDirectory(at: unzipDirectoryURL, withIntermediateDirectories: false)
try fileManager.unzipItem(
    at: archiveURL,
    to: unzipDirectoryURL,
    skipCRC32: true
)
```

# Expected Results
Unzipped directory.

# Actual Results
Fails with following error
```
 File already exists: "Can\'t rename \'/Users/.../Dump/.tmp-WRjpwi\' to \'/Users/.../Dump/Preview-Images-Backup.zip\' as it already exists." ('renamex_np' system call failed with '(17) File exists'.)
```
# Regression & Version
`0.9.19`

**Comment by weichsel** [comment]
Can you share a sample project with the archive?
Something seems to be off with your destination directory URL.

**Comment by IgorMuzyka** [comment]
@weichsel there's nothing special with destination directory, it's freshly created and has name of `UUID().uuidString`. The code above however executes on arbitrary `DispatchQueue` if that might be of influence.
I m currently just migrated to `SSZipArchive`.
Also in the process of unarchiving somehow for some reason i get the copy of the archive named with uuid at the path where current archive already is.
This is such an unexpected behavior.
The archive is create in browser with JSZip.
I could try to isolate an example, but probably sometime next week. Current use is in Vapor app from which i would need to strip off a lot not to overshare.

**Comment by weichsel** [comment]
> Also in the process of unarchiving somehow for some reason i get the copy of the archive named with uuid at the path where current archive already is.

How are you constructing your URLs? This definitely shouldn't happen.
Since you are using ZIPFoundation as part of a Vapor project: Which platform is it running on?
