### ISSUE TITLE
Upload to AppStore fail

### ISSUE THREAD

**Issue by shinrenpan** [weichsel/ZIPFoundation#34]
The Framework missing Bundle version.
Installed by Carthage.

![1](https://user-images.githubusercontent.com/1157368/33642665-dd3dcb94-da75-11e7-9cfc-c3c82639c5c1.png)
![2](https://user-images.githubusercontent.com/1157368/33642672-e0cb53e4-da75-11e7-896a-9e1b5ecf33ae.png)

**Comment by weichsel** [comment]
Thank you for reporting this. I just merged a fix into `development`.
It would be great if you can temporarily change your Cartfile to point to `github "weichsel/ZIPFoundation" "development"`. 
Please let me know if `carthage update --no-build`, re-archive & submit now works for you.
