### ISSUE TITLE
ZIPFoundation makes assumptions about memory alignment that are likely to break in forthcoming Swift version

### ISSUE THREAD

**Issue by microtherion** [weichsel/ZIPFoundation#340]
# Summary

`ZIPFoundation` makes assumptions that `Data` and `subdata` in some situations are properly aligned on 4 byte boundaries. These assumptions are in fact not guaranteed by the API and appear to cause crashes on debug build in nightly builds of Swift 6.

# Related Link

There is a rather straightforward fix for this: https://github.com/weichsel/ZIPFoundation/pull/339/files

**Comment by weichsel** [comment]
Merged #339 - Thanks again for the fix!
