### ISSUE TITLE
Implementation question

### ISSUE THREAD

**Issue by matt-curtis** [weichsel/ZIPFoundation#36]
Is there a particular reason why the [Archive iterator scans for the central directory on every access](https://github.com/weichsel/ZIPFoundation/blob/development/Sources/ZIPFoundation/Archive.swift#L180)? Seems to me that for plain reads that value could be cached, unless you expect the ZIP to change underneath you?

Also, would it be possible to publicly expose the central directory record so that the uncompressed & compressed size could be easily read?

**Comment by weichsel** [comment]
You are right, the CD lookup could be cached but I wanted to keep things simple. A cache would require proper invalidation when archives get mutated and from my experience those things seem simple at first but get complex pretty fast :) . 
I haven't profiled CD lookups so far, but I assume that there's some sort of caching going on at the Kernel/FS level anyways - so providing a custom cache might counteract any IO caches that are provided by the system.

I want ot keep the Central Directory structure an implementation detail, but maybe we can add some more file metadata to the `fileAttributes` collection of `Entry`. Can you describe your use case for the `compressed`/`uncompressed` properties?

**Comment by matt-curtis** [comment]
> I haven't profiled CD lookups so far, but I assume that there's some sort of caching going on at the Kernel/FS level anyways - so providing a custom cache might counteract any IO caches that are provided by the system.

How does this work? if the CD lookup is essentially you byte wrangling into a Swift struct, where would the Kernel/FS come in at?

> I want ot keep the Central Directory Structure an implementation detail, but maybe we can add some more file metadata to the fileAttributes collection of Entry. Can you describe your use case for the compressed/uncompressed properties?

Sometimes that information is used to identify or create metadata for a particular archive. For example [ADE pagination](https://wiki.mobileread.com/wiki/Adobe_Digital_Editions#Page_numbers).

**Comment by weichsel** [comment]
> How does this work? if the CD lookup is essentially you byte wrangling into a Swift struct, where would the Kernel/FS come in at?

`readStructure`/`readChunk` perform a `fread` internally.

> Sometimes that information is used to identify or create metadata for a particular archive. For example ADE pagination.

Good point. I will expose those properties when I implement [progress reporting](https://github.com/weichsel/ZIPFoundation/issues/2).
