### ISSUE TITLE
compression_stream is only available on OS X 10.11 or newer

### ISSUE THREAD

**Issue by maximkosov** [weichsel/ZIPFoundation#37]
Build failed when add ZIPFoundation to package with target os version 10.10.

ZIPFoundation seems like the only zip library with SPM support and it has the most modern API. Would be great to have the ability to use it on 10.10 projects at least without compression.

**Comment by weichsel** [comment]
SPM has no parameter for a minimum deployment target yet and it currently always defaults to 10.10 when generating a Xcode Project. (more details here: https://github.com/weichsel/ZIPFoundation/issues/30)
You should be able to get ZIP Foundation working on 10.10 without compression support (or you could link zlib and use the Linux codepath), but I don't plan to add "official" support for pre-iOS 9.0/macOS10.11/tvOS 9.0/watchOS 2.0 versions.
