### ISSUE TITLE
Podspec needs to include Swift Version

### ISSUE THREAD

**Issue by MrMage** [weichsel/ZIPFoundation#47]
# Summary
When trying to build a project with ZIPFoundation included as a CocoaPod, building fails with a `Value for SWIFT_VERSION cannot be empty.` error.

# Steps to Reproduce
1. Add ZIPFoundation as a CocoaPod dependency to your Podfile:

        pod 'libxlsxwriter', :git => 'https://github.com/jmcnamara/libxlsxwriter', :branch => 'master'
2. Run `pod install`.
3. Try to build your project.

# Expected Results
The project builds.

# Actual Results
The error above prevents building.

# Possible Fix
I think it should be sufficient to add a

     s.swift_version = '4.0'

line to the Podspec.

**Comment by weichsel** [comment]
Hello Daniel, 

I just created a small iOS test project to test CocoaPods integration.  
This is the Podfile I am using:

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!
target 'ZIPTest' do
    pod 'ZIPFoundation', '~> 0.9'
end
```

`pod install` worked fine and I also was able to use the library in my test app.  
The dependency you posted points to libxlsxwriter and not ZIP Foundation, maybe this lib is causing your `pod install` errors?  
What CocoaPods/Xcode/Swift versions are you using?

> I think it should be sufficient to add a s.swift_version = '4.0' line to the Podspec.  

I currently only provide a .swift-version file in the project's root. I am not sure if this is sufficient, but I checked several open source Swift projects and most of them also only provide that file (and no `s.swift_version = ...` property in the Podspec).

**Comment by MrMage** [comment]
Hi Thomas,

Thank you for getting back to me so quickly! Turns out that CocoaPods reads the SWIFT_VERSION setting from my project file and sets that on all CocoaPods (as stated at https://github.com/AliSoftware/OHHTTPStubs/issues/231). I had defined that via an `.xcconfig` file, though, which CocoaPods did not pick up. Explicitly stating that setting in the Xcode project fixed things.

Best,
Daniel
