### ISSUE TITLE
Some Item could not be removed for first trying

### ISSUE THREAD

**Issue by cihankom** [weichsel/ZIPFoundation#49]
# Summary
I created Archive object with .update attribute. Then I have tried to remove some items in for loop but some items could not be removed and also archive.remove function is not throwing any exception. I check it whether files still is in zip file or not and some files is still in zip file but a few of file is removed. But if I try to remove second time in same loop for same file , then all items is removed successfully. 

# Steps to Reproduce
Following code is not working expected. Some entry could not be removed from zip file.
```         
archive = Archive(url: zipFilePath, accessMode: .update)
for entry in  entryList {
         try self.zipArchive?.remove(entry)
}
 ```

But if you make for loop like following, the result as expected
```
 archive = Archive(url: zipFilePath, accessMode: .update)
  for entry in  entryList {
       try self.zipArchive?.remove(entry)
                 
        if let stillExist  = self.zipArchive![entry.path] {
              try self.zipArchive?.remove(stillExist)
        }
}
 ```

# Expected Results
All items should be removed successfully

# Actual Results

# Regression & Version

pod 'ZIPFoundation', '~> 0.9'

# Related Link

**Comment by weichsel** [comment]
Thank you for your bug report. 
ZIP Foundation currently doesn't handle the way you are removing entries properly.  
The underlying problem is, that after the first removal, the relative offsets stored in each `entry` no longer match the positions in the `archive` file. 

I will leave the issue open until I found out a solution for the "remove during iteration" use case.
In the meantime, you can try the following workaround:

```swift
guard let archive = Archive(url: archiveURL, accessMode: .update) else { return }
let entryPaths = archive.map{ $0.path }

for path in entryPaths {
    guard let entry = archive[path] else { continue }
    try? archive.remove(entry)
}
```

**Comment by cihankom** [comment]
Your workaround is working. Thanks for your help.

**Comment by ajc-1924** [comment]
sff dndd sms smsm

**Comment by ajc-1924** [comment]
First of all, I would like to thank you for creating the ZIPFoundation framework.
I am trying to use it in my xcode 12 swift 5.3 application. Btw, I am new at coding with swift.
I have a .tar.gz file which I am trying to unzip. 
the file is ok. I tested it from the command line and it extracts properly.

the first question is does ZIPFoundation handles .tar.gz files?

I am using the same code snippet that you used:

do{
        try fileManager.createDirectory(at: destURL, withIntermediateDirectories: true, attributes: nil)
        
        try fileManager.unzipItem(at: sourceURL, to: destURL)
    }catch{
        print("Extraction of ZIP archive failed with error:\(error)")
    }

I get error: unreadableArchive.

and when I used zipinfo, it reports that:

$ zipinfo filename.tar.gz 
Archive:  filename.tar.gz
[filename.tar.gz]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
zipinfo:  cannot find zipfile directory in one of filename.tar.gz or
          filename.tar.gz.zip, and cannot find filename.tar.gz.ZIP, period.
do you have another example that shows how to handle this type of file?
thank you very much for your help

**Comment by weichsel** [comment]
ZIP Foundation only handles .zip files and therefore can not read or write tar.gz archives. 
ZIP and TAR are completely different file formats.

**Comment by ajc-1924** [comment]
Hi Thomas,
I appreciate your reply.
Do you know of a framework that can be used to extract data from a tar file
to be used in swift for IOS?

Thanks,

**Comment by weichsel** [comment]
No, sorry - never had to untar anything on iOS yet.  
But there seem to be some open source projects (I never tried them though).
I saw only Obj-C based ones (tarkit, NVHTarGzip) during a brief look - but you should be able to use those from Swift.
