### ISSUE TITLE
Traverse through a zip to read and not extract.

### ISSUE THREAD

**Issue by Prince2k3** [weichsel/ZIPFoundation#57]
Is there anyway to traverse through the zip file to read for a certain file  it without extract the file within it? I know it is possible in python was wonder if the library had this feature or something similar.

Thx

**Comment by weichsel** [comment]
Yes, `Archive` conforms to `Sequence` and allows you to iterate over all entries via:
```swift
for entry in archive {
    // ...
}
```
If you know the path of the entry within the archive, you can use subscripting to read a specific entry:
```swift
guard let entry = archive['path/file.txt'] else { return }
```

After retrieving an entry, you can decompress/read it by using the closure based API:
```swift
try archive.extract(entry, consumer: { (data) in
    // ...
})
```

The Readme also contains some information about [entry retrieval](https://github.com/weichsel/ZIPFoundation#accessing-individual-entries) and [closure based reading](https://github.com/weichsel/ZIPFoundation#closure-based-reading-and-writing). 

ZIP Foundation also provides documentation for all public methods, so you can use option+click within Xcode to learn more about the API.

**Comment by Prince2k3** [comment]
Cool that second part is what I was wondering about. How deep I can traverse. 
Thx
