### ISSUE TITLE
error: type 'CocoaError' has no member 'error'

### ISSUE THREAD

**Issue by Prince2k3** [weichsel/ZIPFoundation#59]
# Summary
I am having this issue with library on build when I deploy my code. I am not sure how to resolve this issue. Seems to deal with CocoaError on linux.
```
error: type 'CocoaError' has no member 'error'
            throw CocoaError.error(.fileReadNoSuchFile, userInfo: [NSFilePathErrorKey: sourceURL.path], url: nil)
                  ^~~~~~~~~~ ~~~~~
```
# Steps to Reproduce

I am deploying my code to Vapor Cloud ( I have also tried this on Heroku getting same result )

When deploying the build fails giving error above.

# Expected Results

When deploying the build does not fail and runs the code

# Actual Results

When deploying the build fails giving error above.

# Regression & Version

0.9.5

**Comment by weichsel** [comment]
I already contributed a PR to fix this problem in swift-corelibs-foundation (https://github.com/apple/swift-corelibs-foundation/pull/1420). But my change didn't make it into the Swift 4.1 release. 

I just opened a PR to work around that problem by providing an implementation for non-Darwin platforms that use a Swift version < 4.2. 
It would be great if you can check out the `bugfix/linuxCocoaErrorCompileError` branch and test if this fixes the compile error for you.

**Comment by Prince2k3** [comment]
@weichsel That branch worked! I was able to deploy my build.

**Comment by weichsel** [comment]
Great - Thanks for testing.

**Comment by Prince2k3** [comment]
Will there be a new release for this? Now that the branch is gone I can no longer get this to work.

**Comment by weichsel** [comment]
Yes. This will be part of the next release. In the meantime you can use the `development` branch.
