### ISSUE TITLE
Compress/decompress Data 

### ISSUE THREAD

**Issue by icyield** [weichsel/ZIPFoundation#61]
I would like to compress/decompress Data. If I make the 

`static func compress(size: Int, bufferSize: Int, provider: Provider, consumer: Consumer) `

 public and the corresponding uncompress as well  I can then access them and use the code below to compress/decompress data. 

Could you make these Data+Compression methods public, or provide methods for compress/decompress Data?

====

        var dataOut = Data()
        let string = "My data I want to compress"
        var dataIn: Data? = string.data(using: .utf8)
        let consumer : Consumer = { _ = dataOut.append($0) }
        let provider : Provider  = { position, length in
            return (dataIn?.subdata(in: position..<(position+length)))!
        }
        _ = try Data.compress(size: (dataIn?.count)!, bufferSize: (dataIn?.count)!, provider: provider, consumer: consumer)
        
        var res = Data()
        let consumer2 : Consumer = { _ = res.append($0) }
        let provider2 : Provider  = { position, length in
            return (dataOut.subdata(in: position..<(position+length)))
        }
        _ = try Data.decompress(size: (dataOut.count), bufferSize: (dataOut.count), provider: provider2, consumer: consumer2)
        var t = String(data: res, encoding: .utf8)
        Log.info(t!)

**Comment by weichsel** [comment]
As I want to keep the API of the framework as lean as possible, I try to keep all code parts that are not directly related to ZIP archive handling private.  

But if I understand you correctly, you only require the decompress/compress helper methods in the `Data+Compression` extension without the ZIP functionality of the framework? In that case I'd suggest you just copy that category into your project and add a note about its origin and its license.  ZIP Foundation is licensed under the very permissive MIT license: https://github.com/weichsel/ZIPFoundation/blob/master/LICENSE

**Comment by icyield** [comment]
Thanks for your reply. I would probably just fork on github. 

I have been looking into your code a bit more, and am thinking that it might be better for me to have the Archive take Data (with a dummy file name) and output Data. The reason I'm doing this is to avoid touching the file system, in a cloud app, before sending compressed data to an S3 compatible cloud data store. An archive is better as just compressed data I guess is not very portable.

**Comment by weichsel** [comment]
I don't know enough details about your setup, but as long as your data store is accessible via POSIX file system calls (which ZIP Foundation uses internally) it should be possible to:  
 - stream data into an archive via `addEntry:... provider: { ... }`
 - stream data out of an archive via `extract:... consumer: { ... }`

**Comment by icyield** [comment]
S3 uses a REST API. So basically Data is sent. And on the return Data arrives. 

But is not too different as you have nicely abstracted consumer/producer, as when writing, the consumer is a Data object.  Which in my more limit setup is sent as a single lump via POST to a remote service. Amazon S3 does allowing chunking the data.

If I get the time will look into implementing this, rather than just compressing the Data directly.
