### ISSUE TITLE
This application's bundle identifier does not match its code signing identifier

### ISSUE THREAD

**Issue by yaalisri** [weichsel/ZIPFoundation#64]
# Summary
Getting "This application's bundle identifier does not match its code signing identifier
" error while running the application. Installed the framework using carthage. 

# Steps to Reproduce
Install framework using Carthage and build the application

**Comment by weichsel** [comment]
How did you add the framework?  
What ZIPFoundation/Carhage/Xcode versions are you using?

Did you manually drag `ZIPFoundation.framework` to the "Embedded Binaries" section of your main app's target settings?

Maybe this helps: https://stackoverflow.com/a/34652134/100848
Another thing you could try is to integrate the framework via `cartage update --no-build` and manually add the ZIPFoundation.xcodeproj to your workspace.
