### ISSUE TITLE
No support for Overwrite while unzipping files

### ISSUE THREAD

**Issue by sandeepo2o** [weichsel/ZIPFoundation#67]
**Is your feature request related to a problem? Please describe.**
Throwing exception while unzipping directories with existing files.

**Describe the solution you'd like**
provide unzip function with overwrite parameter as boolean

**Comment by weichsel** [comment]
This is a duplicate of #54 

I will fix this in an upcoming release. In the meantime, you can use the workaround described here:
https://github.com/weichsel/ZIPFoundation/issues/54#issuecomment-374153216
