### ISSUE TITLE
Root entries are not listed on iOS simulator

### ISSUE THREAD

**Issue by timautin** [weichsel/ZIPFoundation#69]
# Summary

I have a file I can read on my iPhone but not on the simulator. The file has been created with objective-zip, you can download it here: http://ewalk.app/test.kmz (KMZ file format is just a ZIP).

# Steps to Reproduce

Open the file on an iOS (9, didn't test others) simulator, no entries are listed. The file cannot be opened by OSX archive utility, but can be with other softwares (like the unarchiver, objective-zip, Google Earth - kmz is a Google Earth file format).

    if  let archive = Archive(url: url, accessMode: .read) {
        
        archive.forEach({ (entry) in
            print("entry: \(entry.path)");
        })
        
        if  let entry = archive["doc.kml"] {
            // we do not arrive here
        }
    }

# Expected Results

ZIPFoundation should list a doc.kml entry located at the root of the file.

# Actual Results

No entry listed.

**Comment by timautin** [comment]
Thanks for the quick answer! That's a no-go for e unfortunately, as my app was previously using objective-zip. That would be awesome if you could update the issue when you'll have added support.

**Comment by weichsel** [comment]
I will leave this issue open so that tracking progress is possible.  
Adding support for ZIP64 is sadly non-trivial so it will take some time until it lands in ZIPFoundation. Most likely this will happen post 1.0.

**Comment by timautin** [comment]
Great thanks! Keep up the good work!
