### ISSUE TITLE
Password Protected Archives

### ISSUE THREAD

**Issue by johnayers84** [weichsel/ZIPFoundation#71]
Is there any intent to handle password protected archives?

**Comment by weichsel** [comment]
Yes, 
This is tracked here: https://github.com/weichsel/ZIPFoundation/issues/25

**Comment by johnayers84** [comment]
Thanks, I stumbled across this after I submitted (sorry!).  My request aside, I think the work you’ve done is great and it’s working awesome in my project, thanks!

**Comment by weichsel** [comment]
No problem. Glad you like it!
