### ISSUE TITLE
compile error on linux  error: no such module 'CZlib'

### ISSUE THREAD

**Issue by sinojelly** [weichsel/ZIPFoundation#73]
compile error on linux

error: no such module 'CZlib'
import CZlib
       ^

I use Ubuntu 16.04
and I have installed zlib1g-dev
$ dpkg -l zlib1g-dev
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                     Version           Architecture      Description
+++-========================-=================-=================-=====================================================
ii  zlib1g-dev:amd64         1:1.2.8.dfsg-2ubu amd64             compression library - development

even I compiled and install zlib, still can not import CZlib
$ dpkg -l zlib
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                     Version           Architecture      Description
+++-========================-=================-=================-=====================================================
ii  zlib                     1.2.11-9          amd64             The compression and decompression library

and there are many zlib and libz so:
jelly@LAPTOP-3CCPNNUI:~/swift-4.1.2-RELEASE-ubuntu16.04/zlib-1.2.11$ sudo find /usr -name "zlib.so*"
/usr/lib/x86_64-linux-gnu/ruby/2.3.0/zlib.so
jelly@LAPTOP-3CCPNNUI:~/swift-4.1.2-RELEASE-ubuntu16.04/zlib-1.2.11$ sudo find /usr -name "libz.so*"
/usr/lib/x86_64-linux-gnu/libz.so
/usr/lib64/libz.so.1
/usr/lib64/libz.so.1.2.11
/usr/local/lib/libz.so
/usr/local/lib/libz.so.1
/usr/local/lib/libz.so.1.2.11

how can i resolve it?

**Comment by weichsel** [comment]
> It seems there is no libz-dev.
`libz-dev` is a virtual package that installs `zlib1g-dev` on Ubuntu - that's fine.

How are you trying to build ZIPFoundation? It has one Swift dependency on Linux (CZLib, which wraps zlib for Swift).
Did you run `swift package resolve`?
