### ISSUE TITLE
Incompatible with extensions such as an iMessage app extension

### ISSUE THREAD

**Issue by AndyDentFree** [weichsel/ZIPFoundation#75]
# Summary
Including in a project to build an iMessage extension gets a linker warning _linking against a dylib which is not safe for use in application extensions_

This would result in app store rejection.

# Steps to Reproduce
- Add the framework using Carthage to an iMessage extension project in XCode 9.4.1
- build and check linker errors

# Expected Results
no errors

# Actual Results
linker warning `linking against a dylib which is not safe for use in application extensions: /XXXXXX/Carthage/Build/iOS/ZIPFoundation.framework/ZIPFoundation`

# Regression & Version
Current version 0.9.6 as per `cartfile.resolved`

# Related Link
- Flint project issue [111](https://github.com/MontanaFlossCo/Flint/issues/111)

**Comment by AndyDentFree** [comment]
With manual setting of General - Deployment Info - App Extensions checkbox "Allow app extension API only" flag is OK
![screen shot 2018-08-17 at 5 16 09 pm](https://user-images.githubusercontent.com/1586093/44259437-0c249500-a244-11e8-828b-a5b577a91062.png)

**Comment by weichsel** [comment]
Andy, thanks for making me aware of this.  
Did you already submit your extension? If you did not experience any problems, I will check if the change has any side effects for non-extension scenarios. If everything works as before, I will enable this setting per default.

**Comment by AndyDentFree** [comment]
I haven't submitted my extension yet but just turning that setting on seems to give no problems compiling.

**Comment by weichsel** [comment]
OK. Thanks.
