### ISSUE TITLE
File not ready to read after extraction

### ISSUE THREAD

**Issue by mirkin** [weichsel/ZIPFoundation#77]
Firstly thank you for the library you have developed.

I'm using a progress for fraction completed, when this is 1 I open the file but the file is corrupt. I've put a delay in the code to wait 3 seconds after it reports the fractionCompleted as 1 and it works as a temporary hack. I'm wondering if the fractionCompleted is reporting 1 to the progress before the file is 100% ready to read or is there a better way to trigger and action using the file when it has been unzipped?

```
self.zipProgress = Progress()
self.zipProgress?.addObserver(self, forKeyPath: "fractionCompleted", options: .new, context: nil)
try archive.extract(entry, to: destinationURL, progress: self.zipProgress)
```

**Comment by weichsel** [comment]
The `totalUnitCount` for the progress is in bytes. Can you check if completion is reported correctly if you use the convenience method `Archive.makeProgressForReading(_ entry: Entry)`. This is a shortcoming of the current progress API. It does not enforce correct unit counts.

**Comment by mirkin** [comment]
I think that method must be internal so I can't call it from outside the class. So I tried
```
self.zipProgress = Progress(totalUnitCount: archive.totalUnitCountForReading(entry))
```
Same error of corrupt data when I try to read the extracted file.
Just in case my code has a mistake at the other end, I'll list it here.
```
override func observeValue(forKeyPath keyPath: String?, of object: Any?, change: [NSKeyValueChangeKey : Any]?, context: UnsafeMutableRawPointer?) {
        if keyPath == "fractionCompleted" {
            if zipProgress?.fractionCompleted == 1 {
                print("***ZIP COMPLETE***")
                removeZipFile()
                zipProgress?.removeObserver(self, forKeyPath: "fractionCompleted")
                DispatchQueue.main.asyncAfter(deadline: .now() + 2.5) {
                    // json was corrupt perhaps zip was cleaning up so try delaying
                    self.loadScales()
                    NotificationCenter.default.post(name: .ScalesDidDownloadUpdate, object: self)
                }
            } else {
                print("f:\(zipProgress?.fractionCompleted) \(zipProgress?.completedUnitCount)")
            }
        } else {
            super.observeValue(forKeyPath: keyPath, of: object, change: change, context: context)
        }
    }
```

**Comment by weichsel** [comment]
ZIP Foundation processes everything synchronously. Do you dispatch your extract operation asynchronously on a queue?

**Comment by mirkin** [comment]
Yes  I'm extracting asynchronously on a queue.

**Comment by weichsel** [comment]
The progress count is incremented _after_ ZIP Foundation has processed the entry content but _before_ the destination file gets closed. (Therefore it's possible that file contents haven't been flushed to disk yet).  
Perhaps it's better to use the progress for user feedback (e.g for progress bars) but not for driving your extraction logic.  
An alternative approach to KVOing `fractionCompleted` would be to notify the next component of your extraction code when `archive.extract(...)` returns. At this point it is guaranteed that the destination file has been written and closed.

**Comment by mirkin** [comment]
Perfect solution, why didn't I think of that?

**Comment by weichsel** [comment]
Glad I could help.
