### ISSUE TITLE
Permission issue iOS app

### ISSUE THREAD

**Issue by StackHelp** [weichsel/ZIPFoundation#84]
let fileManager = FileManager()
        let currentWorkingPath = fileManager.currentDirectoryPath
        var sourceURL = URL(fileURLWithPath: currentWorkingPath)
        sourceURL.appendPathComponent("Templates/template1.zip")
        var destinationURL = URL(fileURLWithPath: currentWorkingPath)
        destinationURL.appendPathComponent("preview/template1")
        var isDir : ObjCBool = false
        if fileManager.fileExists(atPath: destinationURL.path, isDirectory:&isDir) {
            if isDir.boolValue {
                // file exists and is a directory
                print("file exists and is a directory")
            } else {
                // file exists and is not a directory
                print("file exists and is not a directory")
            }
        } else {
            // file does not exist
            print("file does not exist")
            do {
                try fileManager.createDirectory(at: destinationURL, withIntermediateDirectories: true, attributes: nil)
                try fileManager.unzipItem(at: sourceURL, to: destinationURL)
            } catch {
                print("Extraction of ZIP archive failed with error:\(error)")
            }
        }

`You don’t have permission to save the file “template1” in the folder “preview”." UserInfo={NSFilePath=/preview/template1, NSUnderlyingError=0x600001782220 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied`

Is there any code I need to add?

**Comment by StackHelp** [comment]
I am using 0.9.6

**Comment by weichsel** [comment]
`fileManager.currentWorkingDirectory` return `/` - pointing to the file system root.  
You don't have permissions there, so the returned error is correct.  
You need to extract to a writeable location within your apps container. To lookup such paths on iOS you can use e.g. `NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true).first`.
Your source URL is also pointing to a non existent file. To get an URL to an asset in your app bundle, you could use something like  `Bundle.main.url(forResource: "template1", withExtension: "zip")`

**Comment by StackHelp** [comment]
@weichsel Thanks. Great quick support and very good repository. God bless sir :)

**Comment by StackHelp** [comment]
It's working but I am unable to get `index.html` file in directory. Is there any code about that?

        let url = URL(fileURLWithPath: FileManager.documentsDir())
        let pathComponent = url.appendingPathComponent("Preview/template1/index.html")
        let filePath = pathComponent.path
        let fileManager = FileManager.default
        
        if fileManager.fileExists(atPath: filePath) {
            print(filePath)
        } else { print("Not exist") }

This always prints "not exists"
