### ISSUE TITLE
Replace the existed file control by a boolean

### ISSUE THREAD

**Issue by lyc2345** [weichsel/ZIPFoundation#88]
Really awesome tool for zip and unzip.

Respect!

Is possible to add a feature which can control over-write existed files by a boolean?

**Comment by weichsel** [comment]
> Really awesome tool for zip and unzip.  

Thank, you - Happy to provide something useful. 

> Is possible to add a feature which can control over-write existed files by a boolean?  

Yes, this is currently a shortcoming. 
I provided a workaround in an earlier, related issue: https://github.com/weichsel/ZIPFoundation/issues/54#issuecomment-374153216

 plan to implement that via delegation in a future release, where you can set a delegate that gets messaged before the actual unzip operation. (similar to `FileManagerDelegate`).

As your request is very similar to #54, I will close this issue and track the feature request in the earlier one.
