### ISSUE TITLE
Sending multiple files to the same zipURL

### ISSUE THREAD

**Issue by amandasrosa** [weichsel/ZIPFoundation#90]
# Summary
When I am trying to zip multiple pictures on the same zipURL, I can't because the library tries to create again the same zipFile and I get the error.

# Steps to Reproduce
Zip one file (works): try fileManager.zipItem(at: imageURL, to: zipURL)
If I try sending the second image to the same destination: try fileManager.zipItem(at: secondImageURL, to: zipURL) . I got the error. 

# Expected Results
I would like to zip multiple urls on the same zipURL

# Actual Results
Error: "couldn’t be saved in the folder “tmp” because a file with the same name already exists" 

# Regression & Version
'ZIPFoundation', '~> 0.9'

# Related Link

**Comment by amandasrosa** [comment]
Ok, I can send multiple files with:

guard let zip = Archive(url: zipURL, accessMode: .create) else  {
                return
            }
            
            do {
                try zip.addEntry (with: imageURL.lastPathComponent, relativeTo: imageURL.deletingLastPathComponent())
                try zip.addEntry(with: imageThumbnailURL.lastPathComponent, relativeTo: imageThumbnailURL.deletingLastPathComponent())
            } catch {
                print("Adding entry to ZIP archive failed with error:\(error)")
            }


But is there a way of doing it without creating a folder inside zip?

**Comment by weichsel** [comment]
Hi Amanda,

The `FileManager` extension provides convenience methods to compress a single item (either a file or a directory).  

To add arbitrary items from various locations - which seems to be your use case - `Archive.addEntry` is the right choice.  
The path used within the archive, is the first argument of `addEntry`. If this is only a filename, there shouldn't be a directory entry in the archive.  
What is the output of: 
```swift
for entry in archive {
    print("\(entry.path)")
}
```
