### ISSUE TITLE
Extraction of ZIP archive failed with error:unreadableArchive

### ISSUE THREAD

**Issue by SireeshaSiddineni** [weichsel/ZIPFoundation#93]
# Summary
Getting an error
Extraction of ZIP archive failed with error:unreadableArchive

# Steps to Reproduce

        let documentsPath1 = NSURL(fileURLWithPath: NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0])
        let logsPath = documentsPath1.appendingPathComponent("abc.zip")
        let logsPath1 = documentsPath1.appendingPathComponent("abc")
        do
        {
             FileManager.default.createFile(atPath: logsPath!.path, contents: data, attributes: nil)
            try FileManager.default.createDirectory(at: logsPath1!, withIntermediateDirectories: true, attributes: nil)
        }
        catch let error as NSError
        {
            NSLog("Unable to create directory \(error.debugDescription)")
        }
        
        do {
            try FileManager().unzipItem(at: logsPath!, to: logsPath1!)
        } catch {
            print("Extraction of ZIP archive failed with error:\(error)")
        }
        
# Expected Results

Should unzip the file
# Actual Results

# Regression & Version

# Related Link

**Comment by weichsel** [comment]
Can you provide a sample file that demonstrates the issue?  
Where is your `data` object coming from? Are you sure it contains valid ZIP data?

**Comment by SireeshaSiddineni** [comment]
HI @weichsel The zip file contains valid data when trying to unzip manually like when double click on the zip file got the file with valid data.

data is coming from my server url api hit response.

**Comment by weichsel** [comment]
If the ZIP archive is valid, can you please check if your `FileManager.default.createFile` call succeeds.  
Maybe the data does not get written to the file system properly.

**Comment by SireeshaSiddineni** [comment]
FileManager.default.createFile(atPath: logsPath!.path, contents: data, attributes: nil) is creating a file  and I am getting the data in bytes as well

**Comment by weichsel** [comment]
Is it an encrypted ZIP file? ZIP Foundation currently does not support ZIP 64 or encrypted zips.  
If you can share the file, I can have a look.

**Comment by SireeshaSiddineni** [comment]
[abc.zip](https://github.com/weichsel/ZIPFoundation/files/2970002/abc.zip)
Its an xml file

**Comment by weichsel** [comment]
The file you posted is not a valid ZIP file. While it starts with a regular ZIP header, and also contains data, it lacks an End-of-central-directory signature.  
ZIP Foundation currently does not attempt any form of recovery if it encounters an incomplete archive. Applications such as the Archive Utility on macOS implicitly try to recover ZIP entries, even if they are not able to fully parse the index at the end of the file.  
You can use the `zipinfo` command line utility to check if an archive complies with the ZIP specification.  
Do you have control over the way the archive is created? Maybe you can fix the problem there?

**Comment by karkadah** [comment]
Hello, unzip works great but is there any chance to notify when unzipping is done and the file is written and ready for further processing? I am using try archive.extract(entry, to: destinationURL) but can't catch the end. Thank you.

**Comment by weichsel** [comment]
Can you post a sample archive that showcases the issue?
`.extract` runs synchronously and code after the call should be executed after extraction has finished. 
Please note that `DEBUG` builds are very slow and it might take a while until an entry has been processed.

**Comment by karkadah** [comment]
Oh I see now it works just as you say. Thank you.
