### ISSUE TITLE
Compatibility with Swift 5.0

### ISSUE THREAD

**Issue by rlaurb** [weichsel/ZIPFoundation#97]
# Summary
Now that Swift 5 is officially out, it seems appropriate to observe that there are four instances of the following deprecation warning when compiling ZIPFoundation:

` 'withUnsafeBytes' is deprecated: use `withUnsafeBytes<R>(_: (UnsafeRawBufferPointer) throws -> R) rethrows -> R` instead`

Two of the warnings occur in Data+Compression.swift and the other two occur in Data+Serialization.swift.

It would be nice if ZIPFoundation compiled without warnings.

**Comment by weichsel** [comment]
Deprecations will be fixed with the next release. 
I will leave this issue open and reference it in the PR that fixes the warning.

**Comment by rlaurb** [comment]
Thank you.

Cheers,

Rick Aurbach
8233 Tulane Avenue
St. Louis, MO 63132

eMail:     rlaurb@icloud.com
Phone:   314/721-7987

“Be kind to dragons, for thou art crunchy when roasted and taste good with ketchup.” – Sherrilyn Kenyon, author of Dragonswan
