### ISSUE TITLE
unzipItem(at:to:) hangs when unzipping a tiny file

### ISSUE THREAD

**Issue by anthonyc-r** [weichsel/ZIPFoundation#98]
# Summary
When  unzipping a .zip file which contains a very small file, the program hangs indefinitely. 

# Steps to Reproduce
Create a zip of a folder containing a text file with the text "aaaaaaaaaaaaaaaaaaaaaaaaa" (Without quotes).
Attempt to unzip this.

# Expected Results
The program to execute and terminate shortly after.

# Actual Results
The program continues to run indefinitely (or for longer than I was willing to wait).

# Regression & Version
0.9.8

# Related Link
Exact code used to reproduce: https://pastebin.com/HfARVNrs

**Comment by weichsel** [comment]
Thanks for reporting this.  
This seems to be related to a recent change in the SDK that ships with Xcode 10.2. 
Compression.framework no longer marks the stream as `finalized` when processing files where the compressed input is larger than the uncompressed content. (This can happen for very small files that use zlib compression).  
I am already working on a workaround in this branch:
https://github.com/weichsel/ZIPFoundation/tree/bugfix/decompressionStreamTermination

Seems to work so far, but still needs some review and testing.

**Comment by anthonyc-r** [comment]
That's great to hear, thank you!
